/**
 * `sfi vault git enable` — turn the vault into its own git history
 * (P13-GITHIST-enable). Git already IS a versioned property store, so
 * instead of building one: init a repo INSIDE org-kb with a generated
 * .gitignore (graph db, snapshots, caches — the rebuildable/transient
 * surfaces), and let every refresh whose source tree actually changed
 * auto-commit `source/ components/ meta/manifest.json meta/history.jsonl`
 * with a delta-summary message.
 *
 * Non-enabled vaults see ZERO change: the refresh hook is gated on
 * `org-kb/.git` existing. The sourceTreeHash walk ignores dot-entries (and
 * `.git` lives beside `source/`, not inside it), so enabling git never
 * perturbs hash stability or refresh-integrity (pinned by test).
 */

import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { Command } from 'commander';

import { loadVaultConfig } from './refresh.js';

/** The generated ignore list: rebuildable or transient surfaces only. */
export const VAULT_GITIGNORE = `# generated by \`sfi vault git enable\` — rebuildable/transient surfaces
graph/
snapshots/
docs/
meta/extract-cache.json
meta/pulse.json
meta/staleness.json
meta/risk-scores.jsonl
meta/watch.pid
meta/staged-refresh.json
meta/demand-queue.jsonl
meta/org-card.json
meta/refresh-epoch
`;

/** Run git in `cwd`; returns { ok, output } without ever throwing. */
export const runGit = (
  cwd: string,
  args: readonly string[],
): { readonly ok: boolean; readonly output: string } => {
  const r = spawnSync('git', [...args], { cwd, encoding: 'utf8' });
  return {
    ok: r.status === 0,
    output: `${r.stdout ?? ''}${r.stderr ?? ''}`.trim(),
  };
};

/** True when the vault has its own git history enabled. */
export const vaultGitEnabled = (vaultRoot: string): boolean =>
  existsSync(join(vaultRoot, '.git'));

/**
 * Initialize the vault repo + .gitignore + initial commit. Idempotent: an
 * already-enabled vault just reports so.
 */
export const enableVaultGit = async (
  vaultRoot: string,
): Promise<{ readonly ok: boolean; readonly message: string }> => {
  const probe = spawnSync('git', ['--version'], { encoding: 'utf8' });
  if (probe.status !== 0) {
    return { ok: false, message: 'git binary not found on PATH — install git to enable vault history.' };
  }
  if (vaultGitEnabled(vaultRoot)) {
    return { ok: true, message: 'vault git history already enabled (org-kb/.git exists).' };
  }
  const init = runGit(vaultRoot, ['init']);
  if (!init.ok) return { ok: false, message: `git init failed: ${init.output}` };
  // Commits need an identity; CI runners and fresh machines often have no
  // global one. Set a VAULT-LOCAL identity only when none resolves — a
  // user's own global config always wins.
  const identity = runGit(vaultRoot, ['config', 'user.email']);
  if (!identity.ok || identity.output.trim().length === 0) {
    runGit(vaultRoot, ['config', 'user.email', 'sfi-vault@local']);
    runGit(vaultRoot, ['config', 'user.name', 'sf-intelligence vault']);
  }
  await writeFile(join(vaultRoot, '.gitignore'), VAULT_GITIGNORE, 'utf8');
  // `git add -A .` with the generated .gitignore enforcing the boundary —
  // pathspec lists fail wholesale when a file does not exist yet (a fresh
  // vault has no manifest/history until its first refresh).
  runGit(vaultRoot, ['add', '-A', '.']);
  const commit = runGit(vaultRoot, [
    'commit',
    '--no-gpg-sign',
    '-m',
    'sfi vault git enable — initial vault history snapshot',
  ]);
  if (!commit.ok && !/nothing to commit/i.test(commit.output)) {
    return { ok: false, message: `initial commit failed: ${commit.output}` };
  }
  return { ok: true, message: 'vault git history enabled — refreshes with source changes now auto-commit.' };
};

/**
 * Refresh hook: commit the new vault state after a refresh whose source
 * tree CHANGED. Best-effort by contract — a git failure never fails the
 * refresh; a non-enabled vault is a no-op.
 */
export const autoCommitVaultGit = (
  vaultRoot: string,
  message: string,
): { readonly committed: boolean; readonly detail: string } => {
  if (!vaultGitEnabled(vaultRoot)) return { committed: false, detail: 'not enabled' };
  const add = runGit(vaultRoot, ['add', '-A', '.']);
  if (!add.ok) return { committed: false, detail: `git add failed: ${add.output}` };
  const commit = runGit(vaultRoot, ['commit', '--no-gpg-sign', '-m', message]);
  if (!commit.ok) {
    return /nothing to commit/i.test(commit.output)
      ? { committed: false, detail: 'nothing to commit' }
      : { committed: false, detail: `git commit failed: ${commit.output}` };
  }
  return { committed: true, detail: commit.output.split('\n')[0] ?? 'committed' };
};

export const registerVaultCommand = (program: Command): void => {
  const vault = program
    .command('vault')
    .description('Vault maintenance: git history (enable/status).');
  const git = vault.command('git').description('Vault-local git history (P13-GITHIST).');
  git
    .command('enable')
    .description(
      'Init a git repo INSIDE org-kb with a generated .gitignore (graph/, snapshots/, caches — rebuildable surfaces). After enabling, every refresh whose source tree changed auto-commits source/ + components/ + manifest + history with a delta summary. Read-only to Salesforce; local files only.',
    )
    .action(async (): Promise<void> => {
      const config = await loadVaultConfig(process.cwd());
      if (!config.ok) {
        process.stderr.write(`${config.error}\n`);
        process.exit(1);
      }
      const r = await enableVaultGit(config.value.vaultRoot);
      process.stdout.write(`${r.message}\n`);
      if (!r.ok) process.exit(1);
    });
  git
    .command('status')
    .description('Report whether vault git history is enabled and the last commit.')
    .action(async (): Promise<void> => {
      const config = await loadVaultConfig(process.cwd());
      if (!config.ok) {
        process.stderr.write(`${config.error}\n`);
        process.exit(1);
      }
      const root = config.value.vaultRoot;
      if (!vaultGitEnabled(root)) {
        process.stdout.write('vault git history: NOT enabled (run `sfi vault git enable`).\n');
        return;
      }
      const last = runGit(root, ['log', '-1', '--format=%h %ad %s', '--date=iso']);
      process.stdout.write(`vault git history: enabled\nlast commit: ${last.ok ? last.output : '(none yet)'}\n`);
    });
};
