/**
 * GENERATED FILE — per-tool utterance corpus for the semantic funnel.
 *
 * Provenance: distilled from the router-v2 recall diagnosis (2026-07)
 * — 1,125 SYNTHETIC ask-phrasings covering all registered tools, written to
 * bridge the vocabulary gap between how users actually phrase questions
 * ("what stops me from saving", "who has this perm set", "what writes to X")
 * and the technical language of the MCP tool descriptions. Every utterance is
 * generic Salesforce vocabulary with placeholder entities (<Object>, <Field>,
 * <FlowName>, standard objects like Account/Contact/Case) — NO real-org
 * identifiers, enforced by scripts/scan-org-leaks.mjs and the release guard.
 *
 * Consumed by semantic-funnel.ts buildToolDocs(): each tool's index document
 * is its MCP description + capability example questions + THESE utterances,
 * so the TF-IDF funnel can rank a tool for phrasings its description never
 * used. Adding/removing utterances shifts every term's IDF — the
 * funnel-recall / semantic-funnel tests are the referee for any edit.
 *
 * To regenerate: rebuild the utterance corpus from the current miss-list
 * diagnosis (one JSON object: full `sfi.*` tool name -> string[] of
 * utterances, every registry tool present) and re-emit this module with the
 * same shape. test/funnel-utterances.test.ts enforces exact key parity with
 * the V01_TOOLS registry, so a renamed/added/removed tool fails the build
 * until this corpus is regenerated.
 */

/** Per-tool synthetic ask-phrasings, keyed by full `sfi.*` tool name. */
export const FUNNEL_UTTERANCES: Readonly<Record<string, readonly string[]>> = {
  'sfi.search_components': [
    'is there a validation rule that stops me from saving a Contact without a Status__c?',
    'find me a validation rule touching Priority__c',
    'does a rule exist blocking Case creation if Subject is blank?',
    'is there a rule that fires when Opportunity.Stage = Closed Lost',
    'search for anything referencing <PermissionName>',
    'find a validation rule whose formula checks $Permission.<X>',
    'what custom permission does <PermSet> do — sounds like it skips a validation',
    'I heard we have a flow that assigns Cases to the Support queue — which one and what\'s the criteria?',
    'is there a workflow rule that emails someone when a Lead is converted?',
    'find anything that references the External_Id__c field on Account',
    'do we have a duplicate rule on Contact?',
    'search for all components that touch the Amount__c field',
    'what validation rules exist on the Order object?',
    'show me every component that references the <PermSet> permission set',
    'is there an approval process on Opportunity?',
    'find me anything that blocks record creation when a required field is empty',
    // biz-user register (router-v2 R2): existence-check with a look-inside.
    'does a <Object> object exist in this org? I want to see its fields',
  ],
  'sfi.resolve': [
    'pull the <vague-field-name> field — <PermSet> implies we have one',
    'i keep seeing <prefix>__ everywhere — whats that prefix',
    'do we have a field for tracking renewal dates?',
    'find me the field that stores the customer tier',
    'I think there\'s a flow called something like case assignment — look it up',
    'look up the thing that sounds like external identifier on Account',
    'we have something called Priority — is that a field or a picklist value?',
    'find the object that handles billing addresses',
    'is there a permission set that sounds like it grants read-only access to financials?',
    'I keep hearing about a <fuzzy-name> flow — can you find it?',
    'what\'s the canonical name for the field that stores the SLA deadline?',
    'look up Status__c — which object is it on?',
    'do we have anything for tracking escalation dates on Case?',
    // biz-user register (router-v2 R2): nickname-existence and
    // component-type-confusion phrasings ("is that a flow or a trigger").
    'I keep calling it the \'<nickname>\' object — does this org have something like that?',
    'is <ComponentName> a flow or a trigger? I can\'t tell from the name',
    'what type of component is <ComponentName> — an Apex class or a flow?',
  ],
  'sfi.capabilities': [
    'what can you actually do?',
    'what tools do you have available?',
    'give me a rundown of everything I can ask you about',
    'what kinds of questions can you answer about this org?',
    'what\'s your capability list?',
    'I\'m new here — what does this thing do?',
    'show me the full menu of what you support',
  ],
  'sfi.list_analyses': [
    'what analyses have been run on this org?',
    'show me all saved analyses',
    'which analysis reports are available?',
    'list the pre-built analyses I can run',
    'what analysis types does this support?',
    'what named analyses can I run against this org?',
  ],
  'sfi.describe_analysis': [
    'what does the tech debt analysis actually check?',
    'explain what the permission risk analysis looks at',
    'describe what the coverage report covers',
    'what does the org risk report measure exactly?',
    'what inputs does the automation risk analysis need?',
    'how does the code quality audit work under the hood?',
  ],
  'sfi.run_analysis': [
    'run the tech debt analysis now',
    'kick off the permission risk report',
    'execute the automation risk analysis',
    'can you run the coverage report for me?',
    'start the org risk report analysis',
    'go ahead and run the coverage report analysis',
  ],
  'sfi.synthesize_answer': [
    'can you pull together everything you know about how Case assignment works?',
    'synthesize an answer about our sharing model for Opportunity',
    'give me a consolidated view of everything touching the Lead conversion process',
    'piece together what you know about our CPQ setup',
    'summarize all the relevant metadata about our Account hierarchy',
    'combine everything you found and give me a clean answer',
  ],
  'sfi.route_question': [
    'I\'m not sure which tool to use — who can edit the Amount__c field?',
    'figure out the best way to answer: why did this record change?',
    'where do I even start to understand why a flow failed?',
    'I have a broad question about our data model — route me to the right thing',
    'what\'s the best tool to find out if a field is used anywhere?',
    'I\'m not sure which tool answers \'what runs on Contact save\' — which one?',
  ],
  'sfi.org_pulse': [
    'give me a quick health snapshot of the org',
    'what\'s the current state of this Salesforce instance?',
    'pulse check — is this org healthy?',
    'quick status: how is the org doing right now?',
    'is there anything alarming about this org at a glance?',
    'one-liner on org health',
    // biz-user register (router-v2 R2): "who is changing things" asked as a
    // people question, not a metadata question.
    'who has been modifying things in this org the most?',
    'who are the top contributors to changes in this org lately?',
    'who\'s been making the most changes to this org lately?',
  ],
  'sfi.org_card': [
    'show me the org\'s basic info — edition, limits, creation date',
    'what edition is this org?',
    'give me the org ID and basic metadata',
    'what sandbox type is this?',
    'who\'s the org admin and what\'s the org name?',
    'pull the orientation snapshot for this org',
  ],
  'sfi.fleet_find': [
    'find all orgs in the fleet that have the <Package> package installed',
    'which orgs in our fleet have Flows on the Case object?',
    'search across all our orgs for a specific component',
    'show me which orgs have this permission set configured',
    'which fleet orgs still have Process Builder active?',
    'search all registered orgs for a component called <ComponentName>',
  ],
  'sfi.fleet_drift_ranking': [
    'which orgs in our fleet have drifted most from the baseline?',
    'rank our orgs by how much they\'ve diverged from each other',
    'show me which fleet orgs are most out of sync',
    'drift ranking across our sandbox fleet',
    'which org has changed the most since last baseline?',
    'which of our orgs is most out of date and needs a refresh first?',
  ],
  'sfi.get_component': [
    'show me the full metadata for the <FlowName> flow',
    'pull up the <ApexClass> class definition',
    'get me the raw component data for the Contact validation rule',
    'fetch the permission set definition for <PermSet>',
    'show me the layout metadata for Case',
    'pull the full metadata for <FlowName>',
  ],
  'sfi.list_components': [
    'whats on the Account object — give me the whole field list',
    'list all custom fields on Contact',
    'show me every flow on this org',
    'what record types exist on Case?',
    'enumerate all permission sets',
    'show me all active validation rules on Contact',
    'Which duplicate matching rules exist but are inactive — deployed and forgotten?',
    'list every Apex class in this org',
    'what custom objects do we have?',
    'show me all the triggers on Account',
    'what approval processes are deployed?',
    'list all custom labels',
    'give me every email template in the org',
  ],
  'sfi.get_edges': [
    'what are the edges between <ApexClass> and the objects it touches?',
    'show me all dependency edges for the <FlowName> flow',
    'what connects to <ComponentName> in the metadata graph?',
    'enumerate the graph edges for this permission set',
    'which components does <ApexClass> directly reference?',
    'list all the outgoing dependencies from Account',
  ],
  'sfi.get_subgraph': [
    'give me the dependency subgraph around the Case object',
    'show me everything in the graph connected to <ApexClass>',
    'pull the subgraph for flows touching Opportunity',
    'what\'s the local neighborhood of <ComponentName> in the dependency graph?',
    'give me a slice of the graph centered on <FlowName>',
    'show me a 2-hop neighborhood around the Contact object',
  ],
  'sfi.search_apex_source': [
    'search the Apex code for any reference to External_Id__c',
    'find all Apex that calls Database.insert on Contact',
    'grep the codebase for \'SOQL injection\'',
    'which Apex classes reference the <PermSet> permission?',
    'find Apex source that contains a hardcoded email address',
    'search Apex for any class that uses future methods',
    'look for Apex code that queries the Order object',
  ],
  'sfi.search_flow_metadata': [
    'I heard we have a flow that assigns Cases to the Support queue — which one and what\'s the criteria?',
    'find a flow that references Priority__c',
    'search flow XML for a specific field value',
    'which flows contain a Decision element?',
    'find flows that call the <ApexClass> Apex class',
    'which flows have a Get Records step on the Account object?',
    'search for flows that send emails',
    'find every flow that creates an Opportunity',
  ],
  'sfi.get_naming_convention_report': [
    'do our field names follow any consistent pattern?',
    'is there a naming convention for our custom objects?',
    'are our Apex class names consistent?',
    'what naming patterns do we use for permission sets?',
    'check if our flow names follow a standard',
    'are there naming convention violations in our org?',
  ],
  'sfi.get_manifest': [
    'export a package.xml for all our custom components',
    'give me the manifest of everything in this org',
    'what\'s in the deployment manifest?',
    'show me the package manifest for our custom metadata',
    'generate a manifest I can use for a deployment',
    'what\'s in the current vault manifest?',
  ],
  'sfi.coverage_report': [
    'what\'s our overall Apex test coverage?',
    'give me a coverage summary for all Apex classes',
    'which classes have the lowest test coverage?',
    'are we above the 75% coverage threshold?',
    'show me the coverage report',
    'which triggers have zero test coverage?',
    'overall code coverage percentage for this org',
  ],
  'sfi.retrieve_blindspot_report': [
    'what metadata types are we NOT tracking in our deployments?',
    'show me the retrieval blindspots — what we\'re missing',
    'which metadata is deployed but not in our source control?',
    'what\'s falling through the cracks in our CI/CD pipeline?',
    'are there any metadata types we can\'t retrieve?',
    'what metadata is referenced but not captured in this vault?',
  ],
  'sfi.health_check': [
    'is this org healthy?',
    'run a health check on the org',
    'what\'s wrong with this org?',
    'give me a health assessment',
    'check for obvious issues with this org',
    'is this org in good shape?',
  ],
  'sfi.baseline_acknowledge': [
    'acknowledge the current baseline',
    'mark this as the new baseline',
    'accept the current state as baseline',
    'set the baseline to today\'s snapshot',
    'confirm I\'ve reviewed the baseline findings',
    'suppress this heuristic finding so it stops showing up',
  ],
  'sfi.baseline_status': [
    'what was the baseline state of the org?',
    'show me what changed since the baseline',
    'when was the last baseline taken?',
    'is the org still at baseline or has it drifted?',
    'compare current state to baseline',
    'which findings have been suppressed in the SAST baseline?',
  ],
  'sfi.live_describe': [
    'describe the Case object — fields, picklists, everything',
    'what fields does the Contact object have in the live org?',
    'pull the live object description for Opportunity',
    'show me the actual picklist values for Status on Case right now',
    'describe Order to me — what fields exist in production?',
    'describe the Account sObject from the live org',
  ],
  'sfi.live_stale_check': [
    'is the vault up to date or stale?',
    'when was the last refresh?',
    'how old is the cached metadata?',
    'is this data current or should I refresh?',
    'check if the vault needs refreshing',
    'has the live org changed since the last vault refresh?',
  ],
  'sfi.live_count': [
    'how many Contacts are in the org?',
    'count all open Cases',
    'how many Opportunities are in Closed Won stage?',
    'how many Accounts exist in production?',
    'total number of active leads',
    'how many open Cases are there right now?',
  ],
  'sfi.live_sample': [
    'show me a few sample Contact records',
    'give me some example Cases to look at',
    'pull a random sample of Opportunity records',
    'show me what Account data actually looks like',
    'grab a handful of Order records for me to inspect',
    'give me a sample of 10 Opportunities with Stage = Prospecting',
    // biz-user register (router-v2 R2): single-record lookup by an id the
    // user has in hand, asking for every field value.
    'can you pull up the specific record for id <RecordId>? I need to see all their field values',
    'show me one actual record with every field value filled in',
  ],
  'sfi.live_field_population': [
    'what percentage of Contacts have the Email field filled in?',
    'how populated is Priority__c on Case?',
    'which fields on Account are mostly empty?',
    'what\'s the fill rate for Amount__c on Opportunity?',
    'are users actually filling in the Description field on Case?',
    'what percentage of Contacts have the Mobile field filled in?',
  ],
  'sfi.live_group_count': [
    'how many users are in the Support group?',
    'count the members of each public group',
    'how many people are in the queue right now?',
    'show me group sizes across all public groups',
    'how many members does the Sales territory group have?',
    'how are Cases distributed by Status right now?',
    // biz-user register (router-v2 R2): distribution-by-field phrasing.
    'how are <Object> records distributed by their Type field?',
    'breakdown of records by picklist value — how many land in each bucket?',
  ],
  'sfi.live_stale_records': [
    'which Cases haven\'t been updated in over 90 days?',
    'show me Opportunities that have been sitting in the same stage for months',
    'find Leads that are more than 6 months old and still open',
    'which Accounts haven\'t had any activity in a year?',
    'stale Contacts — people we haven\'t touched in forever',
    'which Accounts haven\'t been updated in over 180 days?',
  ],
  'sfi.live_recent_activity': [
    'what\'s changed in the org in the last week?',
    'show me recently modified records',
    'what was last touched on the Contact object?',
    'recent activity on Opportunity — who\'s been updating records?',
    'what records have been created in the last 24 hours?',
    'what Leads were created in the last 7 days?',
  ],
  'sfi.live_aggregate': [
    'what\'s the total pipeline value by stage?',
    'average Case resolution time',
    'sum of Amount__c on open Opportunities',
    'count and sum of Orders by status',
    'aggregate the revenue by Account region',
    'what\'s the average Opportunity Amount across open deals?',
  ],
  'sfi.live_duplicate_check': [
    'do we have duplicate Contacts in the org?',
    'find duplicate Accounts by name and email',
    'how many duplicate Lead records do we have?',
    'show me potential duplicate Opportunities',
    'run a duplicate check on Contact',
    'are there any duplicate email addresses on Contact?',
  ],
  'sfi.live_owner_breakdown': [
    'who owns the most Opportunities?',
    'show me Case distribution by owner',
    'which reps have the most open Leads?',
    'breakdown of Accounts by owner',
    'how are Contacts distributed across sales reps?',
    'how many Cases does each queue own right now?',
  ],
  'sfi.live_storage_by_object': [
    'which objects are taking up the most storage?',
    'how much data storage is the Case object using?',
    'show me storage consumption broken down by object',
    'which objects have the most records?',
    'storage breakdown — where is the data?',
    'which objects are taking up the most storage?',
  ],
  'sfi.live_org_limits': [
    'are we close to any governor limits?',
    'how much API call budget do we have left today?',
    'show me current org limits and usage',
    'are we near our data storage limit?',
    'what limits is this org approaching?',
    'how close are we to hitting any governor limits?',
  ],
  'sfi.live_inactive_users': [
    'which users haven\'t logged in recently?',
    'show me inactive Salesforce users',
    'who hasn\'t logged in in over 90 days?',
    'list users that are burning licenses but not active',
    'find users we should probably deactivate',
    'who hasn\'t logged in for more than 60 days?',
  ],
  'sfi.live_license_usage': [
    'how many Salesforce licenses are we using?',
    'show me license utilization',
    'how many licenses are available vs consumed?',
    'are we over or under our license count?',
    'which license types do we have and how many are used?',
    'how many Salesforce licenses are actually being used vs assigned?',
  ],
  'sfi.live_consent': [
    'which Contacts have opted out of email?',
    'show me consent status for marketing contacts',
    'how many people have unsubscribed?',
    'what\'s the email opt-out rate?',
    'show me GDPR consent flags on Contact',
    'do I have live org access enabled for this session?',
  ],
  'sfi.live_report_usage': [
    'which reports are actually being run?',
    'show me report usage stats',
    'what are the most popular reports?',
    'which reports have never been run?',
    'find reports that nobody has opened in 6 months',
    'which reports haven\'t been run in over 6 months?',
  ],
  'sfi.live_folder_access': [
    'who has access to the Sales reports folder?',
    'show me report folder permissions',
    'which users can see the Executive dashboards folder?',
    'who can access the shared document library?',
    'folder-level access for the Finance reports',
    'are any report or dashboard folders publicly accessible?',
    // biz-user register (router-v2 R2): single-report ownership question.
    'the <ReportName> report — who owns it and who can run it?',
  ],
  'sfi.live_email_template_usage': [
    'which email templates are actually being used?',
    'show me email template utilization stats',
    'are there email templates nobody is using?',
    'what templates are being sent most frequently?',
    'which email templates are dead — never triggered?',
    'which email templates are using Classic format instead of Lightning?',
  ],
  'sfi.live_org_health': [
    'how healthy is this org right now — live check',
    'live health status of the org',
    'run a live health assessment',
    'anything actively broken in the org right now?',
    'live org health snapshot',
    'are there any failed async jobs or paused flow interviews right now?',
  ],
  'sfi.live_automation_fired': [
    'which flows have actually fired recently?',
    'show me automation execution history',
    'has the <FlowName> flow run in the last week?',
    'which triggers fired yesterday?',
    'what automation has been active recently?',
    'does the <FlowName> flow actually run in production or is it dead?',
  ],
  'sfi.live_picklist_usage': [
    'which picklist values on Status are actually being used?',
    'show me picklist value usage for Case.Priority',
    'which Stage values on Opportunity are most common?',
    'are there any picklist values that nobody selects?',
    'picklist value distribution on Contact.LeadSource',
    'which Stage values on Opportunity are never actually used in production?',
  ],
  'sfi.live_budget': [
    'what\'s our API call usage vs budget this month?',
    'show me current spending against limits',
    'how much of our governor budget are we consuming?',
    'are we on track to hit any limits this month?',
    'live budget check — API, storage, everything',
    'how many live queries have I used this session?',
  ],
  'sfi.org_risk_report': [
    'Give me the bottom line: three sentences on whether I should be confident or worried about this org going into production.',
    'I have a leadership offsite next week and I want to tell a clean story about the state of our Salesforce platform — the good, the bad',
    'what\'s the health of this org?',
    'is this org production-ready?',
    'what are the biggest risks in this org?',
    'give me a risk summary for this org',
    'executive summary of org risk',
    'what should I be worried about before we go live?',
    'pull together the top risks I need to present to leadership',
    'is there anything that would block a production release right now?',
    // biz-user register (router-v2 R2): quality asked as a grade.
    'is our Salesforce org well-architected? would you give it a passing grade?',
    'if an outside expert graded this org\'s setup, what would they flag?',
  ],
  'sfi.field_cleanup_candidates': [
    'which fields can we safely delete?',
    'show me fields that are never populated',
    'what custom fields are candidates for cleanup?',
    'find fields that nobody uses and we could remove',
    'which deprecated fields should we clean up?',
    'list empty fields on Contact that are safe to remove',
  ],
  'sfi.automation_risk_report': [
    'which of our flows and triggers are high risk?',
    'show me automation that could cause problems',
    'what\'s the riskiest automation in this org?',
    'find automations that could hit governor limits',
    'which flows run synchronously and could slow things down?',
    'automation risk overview — what should we fix first?',
  ],
  'sfi.permission_risk_report': [
    'who has too much access in this org?',
    'which users have Modify All permissions they shouldn\'t?',
    'show me permission risks — overprivileged users',
    'find profiles that have more access than they need',
    'which permission sets grant dangerous access?',
    'security risks from permissions — give me the highlights',
  ],
  'sfi.release_readiness_report': [
    'is this org ready for the next release?',
    'give me a release readiness assessment',
    'what blockers exist before we can deploy?',
    'are we ready to promote to production?',
    'show me the release readiness checklist',
    'what do we need to fix before the next release?',
  ],
  'sfi.get_impact': [
    'what\'s the impact of changing <ComponentName>?',
    'show me what gets affected if I delete <Field__c>',
    'impact analysis for modifying the <FlowName> flow',
    'what would break if I change <ApexClass>?',
    'downstream impact of removing <ComponentName>',
    'what breaks if I delete the <Field__c> field on Account?',
  ],
  'sfi.blast_radius_live': [
    'blast radius of changing <Object>.<Field> from currency to text',
    'live blast radius if I deactivate <FlowName>',
    'how many records would be affected if I change this field?',
    'what\'s the blast radius of making Priority__c required on Case?',
    'if I change this picklist value, how many records does that hit?',
    'how many records would be affected if I remove the External_Id__c field?',
  ],
  'sfi.find_formula_references': [
    'which formula fields reference Priority__c?',
    'find all formulas that use the Amount__c field',
    'what formulas reference the Status field on Case?',
    'are there any formulas that read from External_Id__c?',
    'which roll-up summary fields reference Order.Amount__c?',
    'which formula fields reference the Amount__c field on Opportunity?',
  ],
  'sfi.find_apex_usages': [
    'where is <ApexClass> used in other Apex code?',
    'find all callers of the <Method> method',
    'which Apex classes instantiate <ApexClass>?',
    'what code calls into the <ApexClass> service class?',
    'who uses the <UtilityClass> utility class?',
    'which Apex classes read or write to the Status__c field on Case?',
  ],
  'sfi.effective_permissions': [
    'does the <Profile> profile have access to the Account object?',
    'Lead convert failed with \'missing Edit permission\' — whose perm is that?',
    'what can <Profile> actually do — union of profile plus all their perm sets?',
    'combine <Profile> and <PermSet> and show me the effective access',
    'does assigning <PermSet> override the profile restriction on Case?',
    'what\'s the max-wins access for this user?',
    'can the Sales profile create Opportunity records?',
    'show me the effective field-level security for <Profile> on Contact',
    'what\'s the net permission for a user with <Profile> and <PermSet>?',
    'does this user actually have delete access on Account?',
    'what objects can the <Profile> profile read?',
    'effective read/write/delete access for <Profile> on Order',
  ],
  'sfi.who_can_run': [
    'who can run the <Report> report?',
    'which users are allowed to execute <FlowName>?',
    'who has permission to run this Apex class?',
    'which profiles can see the Sales dashboard?',
    'who can actually execute this scheduled job?',
    'which profiles have permission to run the <FlowName> flow?',
  ],
  'sfi.who_can_access_object': [
    'who can access the Order object?',
    'which profiles and perm sets give read access to Case?',
    'who can see custom object <ObjectName>?',
    'which users have access to the financial data object?',
    'show me everyone who can view Account records',
    'who can see records on the Order object?',
  ],
  'sfi.why_cant_user_see_record': [
    'user can\'t see the Case record — why?',
    'John\'s not seeing the Account — what\'s blocking them?',
    'a user is getting access denied on Opportunity — what\'s wrong?',
    'why is this record invisible to a specific user?',
    'I need to figure out why a user can\'t open this record',
    'user says they get a \'No access\' error on a Contact record — what gives?',
  ],
  'sfi.layout_for_user': [
    'what page layout does <Profile> see on Case?',
    'which layout gets shown to the Sales rep on Opportunity?',
    'show me the layout assignment for the <Profile> profile on Contact',
    'which record type and layout does this user get on Account?',
    'what layout will a support agent see on a Case?',
    'which page layout does the <Profile> profile see on Contact?',
  ],
  'sfi.user_ability': [
    'can <Username> edit Cases?',
    'does this user have permission to delete Contacts?',
    'what can a specific user actually do in the org?',
    'check if <Username> can create Opportunities',
    'what record types can this user access on Case?',
    'what flows can users with the <Profile> profile actually run?',
  ],
  'sfi.profile_security': [
    'how locked down is the <Profile> profile?',
    'show me the security settings for the Sales profile',
    'does <Profile> have any dangerous permissions like Modify All?',
    'what system permissions does the <Profile> profile have?',
    'security review for the support agent profile',
    'which profiles have Apex execute permissions?',
  ],
  'sfi.lightning_pages': [
    'what Lightning pages exist for the Case object?',
    'show me all App Builder pages',
    'which Lightning pages use the <Component> component?',
    'what\'s on the Account record page?',
    'list all Lightning Experience record pages',
    'which Lightning record pages are assigned to the Case object?',
  ],
  'sfi.list_view_sharing': [
    'who can see the \'My Open Cases\' list view?',
    'which list views on Contact are visible to everyone?',
    'show me sharing settings for list views on Opportunity',
    'who has access to the Sales team list view?',
    'list views on Account — who can see which ones?',
    'who can see the \'My Open Cases\' list view on Case?',
  ],
  'sfi.app_access': [
    'which users can see the Sales Cloud app?',
    'who has access to the Service Console?',
    'what apps is the <Profile> profile allowed to use?',
    'which Lightning apps are available to the support team?',
    'show me app access by profile',
    'which profiles can open the Service app?',
  ],
  'sfi.tab_availability': [
    'which tabs can the <Profile> profile see?',
    'is the Order tab visible to sales reps?',
    'which objects have tabs hidden from the support profile?',
    'show me tab settings for the <Profile> profile',
    'which tabs are set to \'Default Off\' for a specific profile?',
    'which tabs are visible to users with the <Profile> profile?',
    // biz-user register (router-v2 R2): imperative "list its tabs" shape.
    'the <Profile> profile — what does it have access to? list its tabs',
  ],
  'sfi.lifecycle_process': [
    'what\'s the Case lifecycle — statuses and transitions?',
    'show me the Opportunity stage progression',
    'what are the valid Lead status transitions?',
    'describe the record lifecycle for Order',
    'what\'s the path an Account goes through from creation to active?',
    'what happens when an Opportunity moves to Closed Won?',
    // biz-user register (router-v2 R2): status-transition asked as "what
    // kicks in when the value flips".
    'when the Status field flips to Resolved, what processes kick in for that value transition?',
    'what happens behind the scenes when a record moves to a new stage?',
  ],
  'sfi.layout_assignments': [
    'which layouts are assigned to which profiles on Case?',
    'show me all layout assignments for Contact',
    'what layout does the admin profile use on Account?',
    'layout to profile mapping on Opportunity',
    'which record type gets which layout on Case?',
    'which profiles are assigned to the Account Layout page layout?',
  ],
  'sfi.integration_map': [
    'what external systems does this org integrate with?',
    'show me all the integrations in this org',
    'what APIs does this Salesforce instance call out to?',
    'which third-party systems are connected?',
    'integration topology — what talks to what?',
    'what external systems is this org connected to?',
  ],
  'sfi.event_subscribers': [
    'what\'s subscribed to the Case platform event?',
    'who listens to <PlatformEvent__e>?',
    'show me all event subscribers in this org',
    'which flows or Apex classes consume platform events?',
    'what processes trigger off <EventName__e>?',
    'who listens to the <Event__e> platform event?',
  ],
  'sfi.guidance': [
    'how should I think about cleaning up this org?',
    'what\'s the recommended approach for migrating Process Builder flows?',
    'guide me through reducing technical debt in our Apex',
    'what\'s best practice for permission set management?',
    'how do I approach a security review in Salesforce?',
    'what\'s the recommended approach for building automation on Salesforce — Flow vs Apex?',
  ],
  'sfi.find_code_usages': [
    'where is <ClassName> referenced in the codebase?',
    'find all usages of <MethodName>',
    'which components use <CustomLabel>?',
    'where is the <ApexClass> class called from?',
    'find everything that references this utility class',
    'which LWC components reference the Account.AnnualRevenue field?',
  ],
  'sfi.lookup_record': [
    'look up the Case record with ID 5001234',
    'find the Account named Acme Corp',
    'pull up the Contact with this email address',
    'look up Order number 1234',
    'fetch the record for this Opportunity',
    'what are the values in the <MetadataRecord__mdt> custom metadata record?',
  ],
  'sfi.explain_field': [
    'what does the External_Id__c field on Contact mean?',
    'explain what Priority__c is used for on Case',
    'what\'s the purpose of Amount__c on Opportunity?',
    'what does this custom field do and where does it come from?',
    'explain the business meaning of Status__c on Order',
    'what are the picklist values on Opportunity.Stage?',
  ],
  'sfi.safe_to_delete_field': [
    'is it safe to delete Priority__c?',
    'can I remove this field without breaking anything?',
    'what would break if I deleted External_Id__c?',
    'is <Field__c> safe to delete?',
    'which fields are safe to remove from Contact?',
    'I want to clean up unused fields — is this one safe to drop?',
  ],
  'sfi.unused_components': [
    'which components in this org are not used anywhere?',
    'find all dead code — Apex classes that are never called',
    'what custom objects have no records and aren\'t referenced?',
    'show me unused permission sets',
    'which flows are deployed but never run?',
    'dead components — Apex, flows, whatever — give me the list',
  ],
  'sfi.find_dependency_cycles': [
    'whats the dependency cycle situation between the Course objects — triggers on <Object1>, <Object2>, <Object3>',
    'we have <Object1> and <Object2> — are they in a dependency loop with each other through triggers or flows?',
    'which Apex classes call each other in a circle?',
    'is there a circular dependency in our trigger code?',
    'do any triggers chain back into themselves?',
    'find recursive call chains in Apex',
    'do we have any circular flow invocations?',
    'which flows call each other in a loop?',
    'check for circular dependencies in the automation layer',
    'are there any infinite loops possible in our trigger/flow setup?',
  ],
  'sfi.apex_test_coverage': [
    'what\'s the test coverage for <ApexClass>?',
    'show me line-level coverage for the <TriggerName> trigger',
    'which lines in <ApexClass> are not covered by tests?',
    'does <ApexClass> meet the 75% coverage threshold?',
    'what\'s the coverage breakdown for the order management class?',
    'which Apex classes have no test coverage at all?',
  ],
  'sfi.automation_build_advisor': [
    'should I build this as a flow or a trigger?',
    'what\'s the recommended automation approach for updating Case on Contact change?',
    'I need to auto-populate a field on save — flow or Apex?',
    'advise me on the best way to automate account territory assignment',
    'how should I implement this business rule — flow, trigger, or process builder?',
    'before I add a new flow on Account, what already runs there?',
  ],
  'sfi.apex_build_advisor': [
    'how should I structure this Apex class?',
    'best practice for writing a trigger on Case?',
    'I\'m building a batch job — any guidance?',
    'recommend an Apex pattern for async processing of Orders',
    'how do I avoid governor limits in this Apex scenario?',
    'before I write Apex for Opportunity, what patterns does existing code use?',
  ],
  'sfi.field_change_advisor': [
    'I want to add a new required field to Case — what should I consider?',
    'advise me on changing the type of Amount__c',
    'what do I need to think about before adding a lookup field to Contact?',
    'guidance on making External_Id__c a unique field',
    'field change advisory for renaming Status__c',
    'give me the full risk briefing before I modify the Priority__c field',
  ],
  'sfi.what_if_change_field_value': [
    'what happens if I change the Stage to Closed Won on these records?',
    'if I bulk-update Priority__c on all open Cases to High, what automation fires?',
    'what changes downstream when I set Status to Active on an Account?',
    'what would happen if someone changes the Amount__c to zero on an Opportunity?',
    'simulate changing Contact.LeadSource from Web to Partner',
    'if someone changes the External_Id__c value on an Account record, what integration breaks?',
  ],
  'sfi.value_change_audit': [
    'who changed the Status__c field on this Case and when?',
    'show me the history of changes to Amount__c on Opportunity',
    'audit trail for Priority__c changes on Case',
    'which users are changing Stage on Opportunity most frequently?',
    'show me all the value changes to External_Id__c in the last month',
    'which fields on Contact are risky to change values on?',
  ],
  'sfi.live_drift_check': [
    'has anything changed in the live org since the last vault refresh?',
    'check if the live org has drifted from the cached metadata',
    'are there new fields in production that aren\'t in our vault?',
    'live drift check — anything deployed since the last snapshot?',
    'compare live org to our stored metadata',
    'has the live org added or removed fields on Account since the last refresh?',
  ],
  'sfi.what_changed_since_refresh': [
    'what\'s been deployed since the last refresh?',
    'show me changes since we last pulled the org metadata',
    'what metadata has changed since the vault was updated?',
    'anything new or modified since the last snapshot?',
    'delta since last refresh — what changed?',
    'what types of components changed in the last refresh?',
  ],
  'sfi.org_history': [
    'show me the change history for this org',
    'what major changes have happened to this org over time?',
    'org changelog — what\'s been modified recently?',
    'historical view of org changes',
    'what was deployed to this org in the last quarter?',
    'show me the refresh history for this org',
  ],
  'sfi.diff_snapshots': [
    'compare the current org snapshot to last month\'s',
    'diff between the two most recent vault snapshots',
    'what changed between snapshot A and snapshot B?',
    'show me the diff between our production and sandbox snapshots',
    'compare two org states and tell me what\'s different',
    'compare the pre-release snapshot to the post-release snapshot',
  ],
  'sfi.churn': [
    'which components change most frequently?',
    'show me high-churn metadata — things we keep modifying',
    'what parts of the org are in constant flux?',
    'which Apex classes get touched every sprint?',
    'high-churn fields on Case — what keeps changing?',
    'which components had the most changes between these two snapshots?',
  ],
  'sfi.trend': [
    'how has the number of Cases grown over time?',
    'show me the trend in Opportunity creation',
    'is our lead volume increasing or decreasing?',
    'trend analysis for Account record creation',
    'how has our automation complexity changed over the last year?',
    'show me component count growth over time across all snapshots',
  ],
  'sfi.compare_components': [
    'compare the Contact layout between sandbox and production',
    'show me the diff between <FlowName> v1 and v2',
    'compare the Case validation rules in two orgs',
    'what\'s different between the <Profile> profile in sandbox vs prod?',
    'compare the <ApexClass> class across environments',
    'are these two record types actually different or just named differently?',
    // biz-user register (router-v2 R2): duplicate-automation confusion.
    'why do we have two triggers on the same object — what does each one do differently?',
  ],
  'sfi.export_manifest': [
    'export the full org manifest',
    'create a package.xml with all custom components',
    'export a deployment manifest for the custom objects',
    'give me a manifest I can use to retrieve this org\'s metadata',
    'export all custom Apex and flows to a manifest',
    'generate a package.xml for these components so I can deploy them',
  ],
  'sfi.pii_inventory': [
    'which fields in this org store personally identifiable information?',
    'show me all PII fields — SSN, email, phone, etc.',
    'GDPR compliance — which fields hold personal data?',
    'inventory of fields that could contain sensitive customer data',
    'which objects store PII that we need to mask in sandboxes?',
    'which fields in this org store personally identifiable information?',
  ],
  'sfi.field_access_audit': [
    'who can read and write the Amount__c field?',
    'which profiles can edit SSN or sensitive financial fields?',
    'show me field-level security for Priority__c across all profiles',
    'who has write access to External_Id__c?',
    'field access audit for Status__c on Case',
    'who has read access to the SSN field on Contact?',
  ],
  'sfi.object_access_audit': [
    'which profiles can create, read, edit, delete Order records?',
    'show me CRUD permissions on Case by profile',
    'who has delete access to Account?',
    'object-level permission audit for Contact',
    'show me which profiles have full CRUD on custom object <ObjectName>',
    'which profiles have Create access on the Case object?',
    // biz-user register (router-v2 R2): group-membership create-access ask.
    'can members of <GroupName> create <Object> records, and where does that access come from?',
  ],
  'sfi.recordtype_availability': [
    'which record types on Case are available to the Support profile?',
    'which record types does the <Profile> profile have access to on Opportunity?',
    'show me record type availability on Account by profile',
    'can the sales rep create a Partner Account record type?',
    'which record types on Contact are visible to the marketing team?',
    'which record types can the <Profile> profile create on Case?',
  ],
  'sfi.org_overview': [
    'break down the codebase footprint for me — LWC vs Aura vs Visualforce, and how much legacy VF debt is there',
    'how many custom objects does this org have?',
    'what are the top objects in this org?',
    'give me a tour of this Salesforce org',
    'what\'s in this org?',
    'quick inventory of the codebase',
    'org summary — what are we working with?',
    'high-level overview of this Salesforce instance',
    'describe this org to me like I just joined the team',
    'how big is this org — fields, flows, classes, the works?',
    'what\'s the overall complexity of this org?',
    'give me a lay of the land for this Salesforce environment',
    // biz-user register (router-v2 R2): the new-joiner altitude idioms.
    'I just joined this team — what\'s the 10,000-foot view of what\'s in this Salesforce org?',
    'give me the bird\'s-eye view of this org for a newcomer',
  ],
  'sfi.domain_clusters': [
    'what functional areas does this org cover?',
    'show me the business domain clusters in this Salesforce org',
    'how is the metadata organized by business function?',
    'what logical groups of objects exist in this org?',
    'cluster the org\'s objects by business domain',
    'can you group the objects in this org into logical domain areas?',
  ],
  'sfi.changed_since': [
    'what changed in the org since last Tuesday?',
    'show me everything modified after January 1st',
    'what metadata was updated this week?',
    'changes since the last release',
    'what\'s been modified since the last sprint?',
    'what components were modified after 2024-01-01?',
  ],
  'sfi.last_modified': [
    'who last modified the <FlowName> flow?',
    'when was the Case layout last changed?',
    'who touched the <ApexClass> class most recently?',
    'when was Priority__c last updated?',
    'last modified date for all custom fields on Contact',
    'when was the Account trigger last changed and by whom?',
  ],
  'sfi.what_happens_on_save': [
    'I need everything that touches Case on save — flows, triggers, PB, validation. Full save cascade please.',
    'Ugh, we keep hitting record-lock errors — which of our automations run concurrently on Contact and could be colliding?',
    'give me a rundown of every automation that involves a Case',
    'what runs when I create a new Opportunity record?',
    'what automation fires on Account update?',
    'what triggers exist on Contact?',
    'if I save an Opportunity, what order does everything fire in?',
    'is there any automation on Order I should know about before adding more?',
    'walk me through everything Salesforce does when I hit Save on a Case',
    'before I add a new flow to Contact, what else is already running on save?',
    'which flows fire synchronously on Lead save?',
    'complete save-event automation inventory for the Account object',
    'what happens behind the scenes when I create a new Contact?',
    // biz-user register (router-v2 R2): terse "show me its automation" shape.
    'the <Object> object — can you show me its automation?',
  ],
  'sfi.why_field_changed': [
    'which flows write to Contact.Status__c?',
    'what sets the value of Opportunity.Amount__c?',
    'who or what writes to Priority__c on Case?',
    'trace every writer to External_Id__c',
    'what automation populates the Status field on Order?',
    'does any trigger or flow update Amount__c?',
    'We loaded leads from an external system and Converted_from_Lead__c is populated — what writes it?',
    'how is Priority__c getting set — is it a user, a flow, or a trigger?',
    'the Status field keeps changing on its own — what\'s causing it?',
    'trace all the things that could write to Case.Status__c',
    'which automation is responsible for populating Amount__c?',
  ],
  'sfi.order_of_execution': [
    'in what order do triggers, flows, and validation rules fire on Case save?',
    'walk me through the Salesforce order of execution for Opportunity',
    'when does before-trigger run vs after-trigger vs flow?',
    'is validation run before or after triggers?',
    'what\'s the order of operations when I save a Contact record?',
    'does the flow run before or after the Apex trigger?',
  ],
  'sfi.explain_flow': [
    'walk me through <FlowName>\'s screens and decisions',
    'walk me thru the <FlowName> fault handling — if a step fails, does it retry, skip, or halt?',
    'Does <FlowName> invoke any Apex, and if so which class/method?',
    'explain the <FlowName> flow end to end — it\'s a screen flow, what\'s the user actually doing in it?',
    'what is <FlowName> for?',
    'when does <FlowName> fire and what does it change?',
    'break down <FlowName> logic',
    'what records does <FlowName> create or update?',
    'I inherited this flow and have no idea what it does — explain it to me',
    'summarize <FlowName> for a non-technical stakeholder',
    'what\'s the happy path through <FlowName>?',
    'does <FlowName> have any error handling?',
    'what variables does <FlowName> use?',
    'which object does <FlowName> primarily operate on?',
    // biz-user register (router-v2 R2): non-technical phrasings from the
    // business-user persona misses — purpose-of-flow asked as a business
    // question, and the "is that a flow or a trigger" type-confusion shape.
    'there\'s a flow called <FlowName> — what is it for? what business process does it support?',
    'what does the <FlowName> flow do for the business?',
    '<FlowName> — is that a flow or a trigger? what does it invoke?',
    'is <ComponentName> an Apex class or a flow? I want to see what it does',
  ],
  'sfi.explain_apex_method': [
    'what does the <MethodName> method in <ApexClass> do?',
    'explain the <MethodName> method — inputs, outputs, side effects',
    'walk me through the logic of <ApexClass>.<MethodName>',
    'what does this method return and what does it modify?',
    'explain the business logic in the <MethodName> method',
    'what does the AccountController class do?',
    // biz-user register (router-v2 R2): whole-class purpose questions and the
    // "Trigger in the name but is it a test class" type-confusion shape.
    'we have an Apex class called <ClassName> — what does it do and what objects does it touch?',
    'is <ClassName> an Apex test class or an actual trigger?',
    'that class has Trigger in its name — is it actually a test class?',
  ],
  'sfi.explain_formula': [
    'what does this formula field actually calculate?',
    'explain the formula on <Field__c> in plain English',
    'break down this validation rule formula for me',
    'what\'s this formula doing — it\'s hard to read',
    'explain the formula logic on Amount__c',
    'what does this formula evaluate to and when?',
  ],
  'sfi.unused_fields_deep': [
    'which fields on Case have zero data and aren\'t referenced by anything?',
    'deep analysis of unused fields — both empty and unreferenced',
    'show me fields that are populated but never read by any automation',
    'find fields that appear in no layouts, no flows, no Apex',
    'which custom fields on Account are completely orphaned?',
    'which fields on Account have zero usage anywhere in the org?',
  ],
  'sfi.process_builder_migration_candidates': [
    'which Process Builder processes should we migrate to Flow?',
    'show me all Process Builder automations still active',
    'which processes are candidates for Flow migration?',
    'what Process Builder is left that we need to retire?',
    'identify Process Builder processes that would be straightforward to convert',
    'which Process Builders should we migrate to Flow first?',
    // biz-user register (router-v2 R2): "sunset/retire" business phrasing.
    'which automation is Salesforce going to sunset that we need to replace?',
    'what legacy automation is being retired that we still depend on?',
  ],
  'sfi.unassigned_permission_sets': [
    'are there permission sets that aren\'t assigned to anyone?',
    'which permission sets are deployed but have zero users?',
    'find permission sets that are effectively dead — no assignments',
    'show me unassigned permission sets we could clean up',
    'permission sets nobody has — are there any?',
    'which permission sets aren\'t assigned to any user?',
    // biz-user register (router-v2 R2): single-perm-set assignment questions
    // ("is X assigned to anyone") — the premise-trap family phrasing.
    'is the <PermSet> permission set assigned to anyone?',
    'is <PermSet> assigned to any active users right now?',
    'who has the <PermSet> permission set assigned and what does it let them do?',
  ],
  'sfi.empty_queues_and_groups': [
    'are there any queues with no members?',
    'show me empty public groups',
    'which queues have nobody in them?',
    'find groups and queues that are effectively abandoned',
    'empty queue check — anything routing to nowhere?',
    'which queues have no members assigned to them?',
  ],
  'sfi.tech_debt_score': [
    'what\'s our overall tech debt score?',
    'how much technical debt does this org carry?',
    'give me a technical debt rating for this Salesforce org',
    'debt score breakdown — what\'s contributing most?',
    'quantify the technical debt in this org',
    'what\'s the overall technical debt score for this org?',
    // biz-user register (router-v2 R2): quality asked as a grade.
    'overall, is this org in good shape or carrying a lot of debt — passing grade or not?',
  ],
  'sfi.code_quality_audit': [
    'how good is our Apex code quality?',
    'find code quality issues in our Apex classes',
    'audit the Apex code for common anti-patterns',
    'show me code quality violations',
    'which Apex classes have the most quality issues?',
    'are there any SOQL queries inside loops in our Apex code?',
  ],
  'sfi.governor_limit_risks': [
    'which parts of our Apex are at risk of hitting governor limits?',
    'find SOQL queries inside loops',
    'which triggers could hit DML limits?',
    'governor limit risk assessment for our Apex',
    'which batch jobs are close to the 50M record limit?',
    'find places where we\'re at risk of CPU timeout',
  ],
  'sfi.find_hardcoded_values': [
    'find hardcoded IDs in the Apex code',
    'which Apex classes have hardcoded email addresses?',
    'find hardcoded profile names in our triggers',
    'are there any hardcoded record type IDs in the code?',
    'show me hardcoded values in Apex that should be in Custom Settings',
    'are there hardcoded IDs or email addresses in our Apex code?',
  ],
  'sfi.crud_fls_audit': [
    'are we enforcing FLS in our Apex?',
    'which Apex classes skip CRUD/FLS checks?',
    'find Apex that queries without checking field-level security',
    'CRUD and FLS audit for our triggers',
    'which classes are vulnerable to privilege escalation via missing FLS?',
    'which Apex classes skip CRUD or FLS checks?',
  ],
  'sfi.test_coverage_gaps': [
    'where are the gaps in our test coverage?',
    'which Apex classes have coverage below 75%?',
    'find untested code paths in our triggers',
    'coverage gaps across all Apex',
    'which classes would block a deployment due to low coverage?',
    'which Apex classes have fake or missing test coverage?',
  ],
  'sfi.what_if_change_field_type': [
    'what happens if I change the type of Case.Priority__c from picklist to text?',
    'blast radius of changing Opportunity.Amount__c from currency to number',
    'if I convert Contact.External_Id__c from Text to EncryptedText, what breaks?',
    'can I safely change <Field> type from Number to Text?',
    'what downstream impact if I make Status__c a lookup instead of text?',
    'impact of changing field type on Account.<Field__c>',
    'I want to change a Text field to a Long Text Area — what\'s the risk?',
    'what breaks if I change the data type of this field?',
    'if I convert this currency field to a formula field, what automation breaks?',
    'blast radius of making Amount__c a formula field instead of editable',
  ],
  'sfi.what_if_remove_picklist_value': [
    'what happens if I delete the \'Pending\' value from Case.Status?',
    'if I remove the \'Cold\' picklist value from Lead.Rating, what records are affected?',
    'can I safely remove the \'Legacy\' stage from Opportunity.StageName?',
    'what breaks if I remove a picklist value that records already use?',
    'impact of removing \'On Hold\' from Case.Status picklist',
    'what breaks if I remove \'Closed - Duplicate\' from Case.Status?',
  ],
  'sfi.what_if_make_field_required': [
    'what happens if I make Priority__c required on Case?',
    'if I make Amount__c required on Opportunity, what existing records would violate that?',
    'impact of making Contact.External_Id__c required',
    'can I safely make this field required without breaking flows?',
    'what automation would break if I make this field mandatory?',
    'what would break if I made Account.Website required?',
    // biz-user register (router-v2 R2): "I want to set X to required" ask.
    'I want to set <Field__c> to required — can you check what flows and Apex would break?',
  ],
  'sfi.what_if_deactivate_flow': [
    'what breaks if I deactivate <FlowName>?',
    'if I turn off this flow, what processes depend on it?',
    'impact of deactivating the Case assignment flow',
    'can I safely deactivate <FlowName> without breaking anything?',
    'what would stop working if I switch off <FlowName>?',
    'what happens if I deactivate the <FlowName> flow?',
    // biz-user register (router-v2 R2): "can you deactivate it safely" and
    // "impact if we turn it off" phrasings (premise-trap family).
    'can you deactivate <FlowName> safely? I need to know what depends on it',
    'we have a <ProcessName> process that runs on these records — what\'s the impact if we turn it off?',
  ],
  'sfi.what_if_disable_trigger': [
    'what breaks if I disable the Contact trigger?',
    'impact of disabling <TriggerName>',
    'if I turn off this trigger, what automation stops running?',
    'can I safely disable the Account trigger?',
    'what would I lose if the Case trigger was off?',
    'if I disable the Account trigger, what stops working?',
  ],
  'sfi.what_if_change_method_signature': [
    'what breaks if I change the signature of <MethodName>?',
    'impact of renaming the <MethodName> method in <ApexClass>',
    'if I add a parameter to <MethodName>, what callers need updating?',
    'which classes call <MethodName> and would be affected by signature change?',
    'can I remove a parameter from <MethodName> without breaking anything?',
    'what breaks if I rename the calculateTotal() method signature?',
  ],
  'sfi.what_if_merge_profiles': [
    'I want to consolidate the permission set group — what would break if I merge <PermSetA> and <PermSetB>?',
    'can I combine the Sales and Sales Manager profiles?',
    'what conflicts exist between <ProfileA> and <ProfileB>?',
    'merge <Profile1> into <Profile2> — what are the collisions?',
    'what permission conflicts come up if I merge these two profiles?',
    'impact of combining two permission sets into one',
    'if I consolidate our three sales profiles into one, what conflicts arise?',
    'what would I lose or gain by merging <PermSet1> and <PermSet2>?',
  ],
  'sfi.what_if_split_profile': [
    'should I split the Admin profile into two?',
    'impact of splitting the <Profile> profile by region',
    'how would I split the Sales profile into read-only and full-access variants?',
    'what\'s involved in splitting a monolithic profile into permission sets?',
    'if I break this profile into two, what do I need to account for?',
    'how would I split the <Profile> profile into multiple permission sets?',
  ],
  'sfi.generate_data_dictionary': [
    'generate a data dictionary for this org',
    'create documentation of all our fields and objects',
    'build a data dictionary I can share with the data team',
    'export field descriptions and types for all custom objects',
    'generate a schema reference document',
    'generate a data dictionary for the Contact object',
    // biz-user register (router-v2 R2): "reference sheet" business phrasing.
    'our business team needs a reference sheet for the <Object> object — field names, types, required vs optional',
    'make a field reference sheet the business team can read',
  ],
  'sfi.generate_admin_handbook': [
    'write an admin handbook for this org',
    'generate a guide for onboarding a new Salesforce admin',
    'create an administrative reference document',
    'build an ops runbook for our Salesforce configuration',
    'document the admin processes in this org',
    'create an admin handbook for this org',
  ],
  'sfi.generate_architecture_overview': [
    'generate an architecture overview for this org',
    'write a technical architecture document',
    'create a high-level architecture summary for stakeholders',
    'document the overall structure of this Salesforce implementation',
    'generate an architecture diagram description for this org',
    'write an architecture overview document for this Salesforce org',
    // biz-user register (router-v2 R2): altitude idiom for leadership.
    'the leadership team wants the 10,000-foot architecture picture of our Salesforce org',
  ],
  'sfi.generate_sharing_summary': [
    'generate a sharing model summary for this org',
    'document how record sharing works in this org',
    'create a sharing and visibility overview',
    'write up the sharing architecture — OWD, roles, sharing rules',
    'generate a sharing model document I can review with security',
    'generate a sharing model summary for this org',
  ],
  'sfi.generate_compliance_report': [
    'generate a compliance report for this org',
    'create a GDPR compliance overview',
    'document our data handling practices from a compliance perspective',
    'produce a security and compliance report',
    'generate a report for an auditor about our data controls',
    'produce a compliance report for data privacy fields in this org',
  ],
  'sfi.generate_onboarding_doc': [
    'generate an onboarding guide for new users',
    'create a getting started document for sales reps',
    'write onboarding documentation for the support team',
    'generate a new hire guide to our Salesforce org',
    'create documentation for someone who has never used our Salesforce before',
    'generate an onboarding document for a new admin joining this org',
  ],
  'sfi.call_graph': [
    'Are there any flows nested inside other flows that make things hard to follow?',
    'what does <ApexClass> call downstream?',
    'trace the full call chain from <TriggerName>',
    'what classes does <ApexClass> depend on transitively?',
    'upstream callers of <ApexClass>',
    'what\'s the call depth on <MethodName>?',
    'show me the full dependency chain for <ApexClass>',
    'which flows invoke other flows?',
    'what\'s the transitive call graph from <ApexClass>?',
    'give me all callers and callees for <ApexClass>',
    'how deep is the call stack for <TriggerName>?',
    'subflow map — which flows call other flows?',
  ],
  'sfi.downstream_effects': [
    'what does changing <Field__c> ripple out to downstream?',
    'show me the downstream effects of modifying <ApexClass>',
    'if I change <FlowName>, what else is affected downstream?',
    'downstream impact of updating the Case status picklist',
    'what does it affect if <ComponentName> changes?',
    'what side effects does the AccountTrigger handler produce downstream?',
    // self-recall reinforcement (router-v2 R2): the two paraphrase-only
    // utterances above ("what else is affected", "what does it affect")
    // shared no vocabulary with the tool's own name and lost the tie to
    // get_impact — anchor the downstream/effects terms.
    'what are the downstream effects if I change <FlowName>?',
    'show downstream effects of a change to <ComponentName>',
  ],
  'sfi.test_coverage_for_method': [
    'what tests cover the <MethodName> method?',
    'which test classes exercise <ApexClass>.<MethodName>?',
    'is there a test for the <MethodName> method?',
    'show me the test coverage for this specific method',
    'what unit tests hit <MethodName>?',
    'which test classes exercise the processPayment() method?',
  ],
  'sfi.meaningful_test_audit': [
    'are our tests actually meaningful or just padding coverage?',
    'which tests have no real assertions?',
    'find tests that just inflate coverage without testing anything',
    'audit our test suite for meaningful assertions',
    'are these tests actually checking anything useful?',
    'which of our test classes have no real assertions — just System.assert(true)?',
  ],
  'sfi.method_reachability': [
    'is <MethodName> reachable from any active flow or trigger?',
    'can this method actually be called in production?',
    'which entry points reach <MethodName>?',
    'is <ApexClass>.<MethodName> dead code?',
    'what paths lead to <MethodName> being invoked?',
    'is the AccountService class reachable from any trigger or REST endpoint?',
  ],
  'sfi.tests_for_change': [
    'which tests do I need to run after changing <ApexClass>?',
    'what test classes cover the code I\'m about to modify?',
    'I changed <FlowName> — which tests should I run?',
    'which tests are relevant to my changes in <ApexClass>?',
    'give me the test suite to run before deploying <ComponentName>',
    'if I change the AccountService and CaseHandler classes, which tests should I run?',
  ],
  'sfi.cdc_subscribers': [
    'what\'s subscribed to Change Data Capture events on Contact?',
    'who listens to CDC events on Account?',
    'show me all Change Data Capture subscribers',
    'which flows or external systems consume CDC events?',
    'what processes react to Account change events?',
    'which flows or triggers listen to Account CDC change events?',
  ],
  'sfi.async_chain_depth': [
    'how deep is the async chain for <ApexClass>?',
    'are there chained queueables that go too deep?',
    'show me the async job chain depth',
    'how many levels of chained async jobs do we have?',
    'which async jobs kick off other async jobs?',
    'how deep is the async call chain from the BatchProcessor class?',
  ],
  'sfi.scheduled_job_catalog': [
    'what scheduled jobs are running in this org?',
    'show me all the scheduled Apex jobs',
    'which batch jobs are scheduled?',
    'list all cron-based jobs in the org',
    'what\'s running on a schedule in this org?',
    'which Apex classes are scheduled to run on a cron schedule?',
  ],
  'sfi.outbound_message_catalog': [
    'what outbound messages are configured?',
    'show me all outbound SOAP messages',
    'which workflow rules send outbound messages?',
    'list all outbound message endpoints',
    'what external systems do we push data to via outbound messages?',
    'what outbound messages does this org send and to which endpoints?',
  ],
  'sfi.endpoint_catalog': [
    'what external endpoints does this org call out to?',
    'show me all named credentials and callout URLs',
    'which Apex classes make HTTP callouts?',
    'list all integration endpoints',
    'what APIs does our Salesforce code talk to?',
    'list all inbound and outbound API endpoints in this org',
  ],
  'sfi.field_meaning': [
    'what does Priority__c mean in our business context?',
    'explain the business purpose of External_Id__c',
    'what\'s the semantic meaning of Status__c on Order?',
    'what does Amount__c represent — is it revenue, cost, or something else?',
    'in plain English, what does this field track?',
    'what does the External_Id__c field on Account actually mean in this org?',
    // biz-user register (router-v2 R2): label-first "what is it really for /
    // who sets it" phrasings from the business-user misses.
    'what is the <Field__c> field really for in this org?',
    'the bad email field — what does it represent and who sets it?',
    'what does that field mean in context — is it set by automation or by users, and what object is it on?',
  ],
  'sfi.disambiguate_concepts': [
    'we have both Priority__c and Case.Priority — which one should I use?',
    'there are three things called Status in this org — which one matters?',
    'Amount__c vs Amount — what\'s the difference?',
    'we have External_Id__c on both Contact and Account — are they related?',
    'clarify the difference between <ConceptA> and <ConceptB> in this org',
    'is \'Status\' the same concept as \'Stage\' in this org or are they different?',
  ],
  'sfi.field_provenance': [
    '<Field__c> is populated but I don\'t know how — is it manually entered or automated?',
    'is Priority__c a formula or is it written by code?',
    'what\'s the source of truth for Contact.External_Id__c?',
    'how does Status__c get its value on Order?',
    'is Amount__c auto-populated or user-entered?',
    'where does the data in this field come from?',
    'is this field set by a trigger, a flow, or does a user type it in?',
    'trace the origin of values in <Field__c>',
    // biz-user register (router-v2 R2): "how does it get its value" shape.
    'how does the <Field__c> field get its value — is it a formula or is something writing to it?',
  ],
  'sfi.find_field_anywhere': [
    'find all objects that have a field called External_Id__c',
    'is there a Priority field on any object in this org?',
    'search for any field named Status across all objects',
    'find fields named Amount__ on any object',
    'which objects have a field called Description?',
    'where is the Priority__c field used across flows, Apex, and layouts?',
  ],
  'sfi.find_semantic_field': [
    'find me a field that tracks customer churn risk',
    'is there a field that stores the contract end date?',
    'find a field related to billing frequency',
    'what field would hold escalation priority?',
    'find a field that represents the customer\'s account tier',
    'do we have a field that stores the customer\'s loyalty tier?',
  ],
  'sfi.find_hardcoded_values_anywhere': [
    'find hardcoded values anywhere — Apex, flows, validation rules, everywhere',
    'search all metadata types for hardcoded email addresses',
    'hardcoded IDs anywhere in the org — not just Apex',
    'find hardcoded profile names in flows too, not just triggers',
    'check flows and validation rules for hardcoded values, not just code',
    'are there hardcoded IDs in our validation rule formulas?',
  ],
  'sfi.find_clone_patterns': [
    'are there Apex classes that look like copy-paste of each other?',
    'find duplicate code patterns in our Apex',
    'which classes have very similar logic that should be refactored?',
    'show me clone candidates in our codebase',
    'find near-duplicate implementations across Apex classes',
    'are there Apex classes that look structurally identical to AccountHandler?',
  ],
  'sfi.find_dead_code': [
    'find Apex methods that are never called',
    'which Apex classes are completely unreferenced?',
    'show me dead code — methods, classes, that nothing calls',
    'find unreachable code paths in our Apex',
    'which classes can I safely delete because nothing uses them?',
    'which Apex classes have no callers and look completely dead?',
  ],
  'sfi.package_impact': [
    'I keep hearing \'<PackageName>\' thrown around. What is it, how deep is it in our org, and are we locked into it?',
    'how entangled is the <Package> package in our customizations?',
    'if we uninstall <Package> what breaks?',
    'what does our org depend on from <Package>?',
    'impact of removing the <PackageName> managed package',
    'show me everything we\'ve built on top of <Package>',
    'how many of our custom components reference <Package> components?',
  ],
  'sfi.cpq_rule_chain': [
    'show me the CPQ pricing rule chain for this product',
    'what CPQ rules fire when configuring a quote?',
    'trace the CPQ rule execution for this product bundle',
    'which CPQ validation and pricing rules apply to Order products?',
    'show me the CPQ rule dependencies',
    'what\'s the order of CPQ product rules that apply to the Bundle product?',
  ],
  'sfi.cpq_quote_template_breakdown': [
    'break down the CPQ quote template structure',
    'what sections and line items does this quote template include?',
    'explain the CPQ quote template layout',
    'show me the components of our primary quote template',
    'what\'s in the standard CPQ quote template?',
    'what sections are in the Standard Quote Template?',
  ],
  'sfi.cpq_dependency_map': [
    'show me the CPQ dependency map',
    'how do CPQ objects relate to each other?',
    'map out the CPQ data model in this org',
    'what CPQ objects and relationships do we have configured?',
    'dependency graph for our CPQ implementation',
    'what SBQQ__ field references exist in this org\'s CPQ configuration?',
  ],
  'sfi.field_360': [
    'give me a 360 view of the Priority__c field',
    'full profile of External_Id__c — who uses it, what sets it, where does it appear',
    'complete field analysis for Amount__c on Opportunity',
    'everything about Status__c on Case — definition, usage, writers, layouts',
    'field 360 for Contact.LeadSource — the full picture',
    'give me the complete picture of the Amount__c field on Opportunity — everything touching it',
  ],
  'sfi.field_lineage': [
    'show me the lineage of Priority__c — where does it come from and where does it go?',
    'trace the data lineage for Amount__c from source to destination',
    'where does External_Id__c originate and how does it flow through the org?',
    'field lineage for Status__c — what populates it and what reads it?',
    'data lineage for a key field on Account',
    'trace where the Opportunity.Amount__c field gets its value from and what it feeds',
  ],
  'sfi.compare_vaults': [
    'compare our production org to our sandbox',
    'show me differences between the two vault snapshots',
    'what\'s different between our dev sandbox and production?',
    'compare the two org configurations',
    'vault diff between production and staging',
    'how does our sandbox differ from production in terms of metadata?',
  ],
  'sfi.promotion_readiness': [
    'is the sandbox ready to promote to production?',
    'what\'s blocking promotion from dev to production?',
    'promotion readiness check for this sandbox',
    'are there any conflicts that would prevent a promotion?',
    'show me what needs to be resolved before we can promote',
    'what sandbox-only components need to be promoted to production?',
  ],
  'sfi.compare_object_across_vaults': [
    'compare the Case object between sandbox and production',
    'how does the Contact object differ across our orgs?',
    'show me differences in the Account schema between two vaults',
    'compare custom object <ObjectName> across environments',
    'Case object schema diff between dev and prod',
    'are the Contact fields the same in sandbox vs production?',
  ],
  'sfi.compare_profile_across_vaults': [
    'compare the Sales profile between sandbox and production',
    'how does <Profile> differ across our orgs?',
    'show me profile differences between environments',
    'compare admin profile between dev and production',
    'which permissions exist in production that are missing from sandbox?',
    'does the <Profile> profile have the same grants in sandbox vs prod?',
  ],
  'sfi.field_mapping_between_objects': [
    'how does the Contact object map to Account?',
    'show me field mappings between Lead and Contact/Account on conversion',
    'what fields get mapped during Case to Opportunity conversion?',
    'field mapping between Order and Quote objects',
    'how do fields on <Object1> map to fields on <Object2>?',
    'map the Lead fields to Contact fields for conversion — what would lose data?',
  ],
  'sfi.datatransform_field_map': [
    'show me the DataTransform field mappings',
    'what field mappings are defined in this DataTransform?',
    'explain the field mapping configuration for this DataTransform',
    'what source and target fields does this DataTransform map?',
    'DataTransform mapping details for the Contact integration',
    'what field mappings does the <DataRaptorName> DataRaptor define?',
  ],
  'sfi.decision_table_browse': [
    'show me the decision tables in this org',
    'browse the Decision Table for pricing rules',
    'what decision tables exist on the Case object?',
    'list all configured decision tables',
    'show me the entries in the routing decision table',
    'what are the input and output parameters of the <DecisionTable> decision table?',
  ],
  'sfi.integration_procedure_chain': [
    'show me the OmniStudio Integration Procedure chain for <IntegrationProcedure>',
    'what does this Integration Procedure call?',
    'trace the IP call chain from <IntegrationProcedure>',
    'which Integration Procedures call each other?',
    'explain the Integration Procedure flow for this use case',
    'walk me through the steps in the <IPName> Integration Procedure',
  ],
  'sfi.omniscript_flow': [
    'walk me through the OmniScript flow for <OmniScriptName>',
    'explain the screens and steps in this OmniScript',
    'what elements does this OmniScript contain?',
    'describe the OmniScript user journey for <OmniScriptName>',
    'what Integration Procedures does this OmniScript call?',
    'what screens and steps does the <OmniScriptName> OmniScript walk the user through?',
  ],
  'sfi.omniuicard_widget_breakdown': [
    'break down the widgets in this OmniUI Card',
    'what components make up this FlexCard?',
    'show me the widget structure of <OmniUiCardName>',
    'explain the layout of this OmniUI Card',
    'what data sources does this FlexCard use?',
    'what widgets are in the <FlexCardName> FlexCard?',
  ],
  'sfi.find_component_usages': [
    'why cant i see the <ComponentName> thing, is it a permission',
    'who has the <PermSet> perm set',
    'who\'s allowed to view the <ComponentName> component?',
    'what uses the <ComponentName> — everywhere it\'s referenced or invoked',
    'where is this flow referenced?',
    'what calls into <ComponentName>?',
    'is <ComponentName> used anywhere?',
    'does anything still use <ComponentName>?',
    'find every place <ComponentName> is referenced',
    'which layouts include the <ComponentName> component?',
    'which flows invoke <ComponentName>?',
    'where is this custom label used?',
    'what uses the <PermSet> permission set — show me all assignments and references',
  ],
  'sfi.installed_package_catalog': [
    'what managed packages are installed in this org?',
    'which packages do we rely on?',
    'i keep seeing <prefix>__ everywhere — whats that prefix and what owns it?',
    'show me all installed AppExchange packages',
    'give me an inventory of all managed packages',
    'which packages are installed and what version are they on?',
    'what third-party packages are we running?',
    'list all packages — namespace, publisher, version',
  ],
  'sfi.annotations': [
    'show me all annotations for <ComponentName>',
    'what notes have been added to this component?',
    'are there any annotations on the <FlowName> flow?',
    'list component annotations in this org',
    'show me existing metadata annotations',
    'what ownership or lifecycle annotations have been added to components?',
  ],
  'sfi.propose_annotation': [
    'suggest an annotation for <ComponentName>',
    'what annotation would you add to this Apex class?',
    'propose a description for the <FlowName> flow',
    'generate an annotation for this component based on what it does',
    'write a description I can add to <ComponentName>',
    'flag the Amount__c field as PII-sensitive so this is recorded',
  ],
  'sfi.component_history': [
    'show me the change history for <ComponentName>',
    'who has modified the <FlowName> flow over time?',
    'what changes have been made to <ApexClass> historically?',
    'component changelog for <ComponentName>',
    'has <ComponentName> changed recently?',
    'when was the AccountTrigger last changed and what did it look like before?',
  ],
  'sfi.component_as_of': [
    'show me what <ComponentName> looked like last month',
    'what did the <FlowName> flow look like before the last change?',
    'show me <ApexClass> as of the January snapshot',
    'what was the state of <ComponentName> at the time of the release?',
    'restore view of <ComponentName> from a specific date',
    'show me what the Account trigger looked like at the v1.0 tag',
  ],
};
