/// <reference types="vitest/globals" />

import { parseApexSpike } from '../src/apex-ast-spike.js';

/**
 * P13-AST-spike — parse-or-fallback on modern Apex syntax. The spike's
 * contract: clean parse on current language features, ok:false (never a
 * throw) on garbage, so a per-file scanner fallback is always possible.
 */

describe('parseApexSpike', () => {
  it('parses a plain class', () => {
    const r = parseApexSpike('public class A { public void go() { Integer i = 1; } }');
    expect(r.ok).toBe(true);
    expect(r.errorCount).toBe(0);
    expect(r.parseMs).toBeGreaterThan(0);
  });

  it('parses the null-coalescing operator (??)', () => {
    const r = parseApexSpike(
      "public class A { String f(String y) { return y ?? 'default'; } }",
    );
    expect(r.ok).toBe(true);
  });

  it('parses safe navigation (?.)', () => {
    const r = parseApexSpike(
      'public class B { public Object g; Object f(B a) { return a?.g; } }',
    );
    expect(r.ok).toBe(true);
  });

  it('parses user-mode DML (insert as user)', () => {
    const r = parseApexSpike(
      'public class C { void f(List<Account> rows) { insert as user rows; } }',
    );
    expect(r.ok).toBe(true);
  });

  it('parses user-mode SOQL (WITH USER_MODE)', () => {
    const r = parseApexSpike(
      'public class D { List<Account> f() { return [SELECT Id FROM Account WITH USER_MODE LIMIT 5]; } }',
    );
    expect(r.ok).toBe(true);
  });

  it('parses a trigger unit', () => {
    const r = parseApexSpike(
      'trigger AccountT on Account (before insert) { System.debug(Trigger.new.size()); }',
      'trigger',
    );
    expect(r.ok).toBe(true);
  });

  it('flags garbage with ok:false and capped errors — never throws (fallback contract)', () => {
    const r = parseApexSpike('this is not apex at all {{{ ;;;');
    expect(r.ok).toBe(false);
    expect(r.errorCount).toBeGreaterThan(0);
    expect(r.errors.length).toBeLessThanOrEqual(5);
    expect(r.errors[0]?.message.length).toBeGreaterThan(0);
  });

  it('inner classes, static + instance members, SOQL-for loops parse clean', () => {
    const r = parseApexSpike(`public class E {
      public class Inner { public Integer n; }
      private static final String K = 'k';
      public void f() {
        for (Account a : [SELECT Id FROM Account WHERE Name != null]) { System.debug(a.Id); }
      }
    }`);
    expect(r.ok).toBe(true);
  });
});

describe('comment-first trigger (P13 fix — kind from extension)', () => {
  it('a trigger opening with a comment parses when kind is passed explicitly', async () => {
    const { extractApexAstEdges } = await import('../src/apex-ast-edges.js');
    const src = `/* generated by dlrs — do not edit */
trigger AccountT on Account (before insert) {
  for (Account a : Trigger.new) { a.Description = 'tagged'; }
}`;
    const sniffed = extractApexAstEdges(src, 'AccountT', {});
    expect(sniffed.parseError).toBeDefined(); // the old failure mode
    const explicit = extractApexAstEdges(src, 'AccountT', { kind: 'trigger' });
    expect(explicit.parseError).toBeUndefined();
    expect(explicit.writes).toContain('Account.Description');
  });
});

describe('unresolved dot-chain roots never emit localvar-shaped targets (P14-PHANTOM-edges)', () => {
  it('emits NO reads/writes keyed by an undeclared variable name', async () => {
    const { extractApexAstEdges } = await import('../src/apex-ast-edges.js');
    // `mystery` is never declared — the resolver cannot type it, so neither
    // the read (mystery.Name) nor the write (mystery.Status__c = ...) may
    // emit an edge keyed on the raw token. The declared `acc` resolves to
    // Account and emits normally.
    const src = [
      'public class PhantomGuard {',
      '  public void run(Account acc) {',
      '    String s = mystery.Name;',
      '    mystery.Status__c = s;',
      '    acc.Industry = s;',
      '  }',
      '}',
    ].join('\n');
    const out = extractApexAstEdges(src, 'PhantomGuard', {});
    const all = [...out.reads, ...out.writes];
    expect(all.some((k) => k.startsWith('mystery.'))).toBe(false);
    expect(out.writes).toContain('Account.Industry');
  });
});

describe('innerTypes surface (P14-USAGE-scanner-fp-downgrade)', () => {
  it('returns the inner class names so the import dedupe can drop typed-receiver scanner FPs', async () => {
    const { extractApexAstEdges } = await import('../src/apex-ast-edges.js');
    const src = [
      'public class Outer {',
      '  public class ReportWrapper { public Id id; }',
      '  public class Row { public String name; }',
      '  public void run() {}',
      '}',
    ].join('\n');
    const out = extractApexAstEdges(src, 'Outer', {});
    expect(out.innerTypes).toEqual(['ReportWrapper', 'Row']);
  });
});
