/// <reference types="vitest/globals" />

import { parseApexSpike } from '../src/apex-ast-spike.js';

/**
 * P13-AST-spike — parse-or-fallback on modern Apex syntax. The spike's
 * contract: clean parse on current language features, ok:false (never a
 * throw) on garbage, so a per-file scanner fallback is always possible.
 */

describe('parseApexSpike', () => {
  it('parses a plain class', () => {
    const r = parseApexSpike('public class A { public void go() { Integer i = 1; } }');
    expect(r.ok).toBe(true);
    expect(r.errorCount).toBe(0);
    expect(r.parseMs).toBeGreaterThan(0);
  });

  it('parses the null-coalescing operator (??)', () => {
    const r = parseApexSpike(
      "public class A { String f(String y) { return y ?? 'default'; } }",
    );
    expect(r.ok).toBe(true);
  });

  it('parses safe navigation (?.)', () => {
    const r = parseApexSpike(
      'public class B { public Object g; Object f(B a) { return a?.g; } }',
    );
    expect(r.ok).toBe(true);
  });

  it('parses user-mode DML (insert as user)', () => {
    const r = parseApexSpike(
      'public class C { void f(List<Account> rows) { insert as user rows; } }',
    );
    expect(r.ok).toBe(true);
  });

  it('parses user-mode SOQL (WITH USER_MODE)', () => {
    const r = parseApexSpike(
      'public class D { List<Account> f() { return [SELECT Id FROM Account WITH USER_MODE LIMIT 5]; } }',
    );
    expect(r.ok).toBe(true);
  });

  it('parses a trigger unit', () => {
    const r = parseApexSpike(
      'trigger AccountT on Account (before insert) { System.debug(Trigger.new.size()); }',
      'trigger',
    );
    expect(r.ok).toBe(true);
  });

  it('flags garbage with ok:false and capped errors — never throws (fallback contract)', () => {
    const r = parseApexSpike('this is not apex at all {{{ ;;;');
    expect(r.ok).toBe(false);
    expect(r.errorCount).toBeGreaterThan(0);
    expect(r.errors.length).toBeLessThanOrEqual(5);
    expect(r.errors[0]?.message.length).toBeGreaterThan(0);
  });

  it('inner classes, static + instance members, SOQL-for loops parse clean', () => {
    const r = parseApexSpike(`public class E {
      public class Inner { public Integer n; }
      private static final String K = 'k';
      public void f() {
        for (Account a : [SELECT Id FROM Account WHERE Name != null]) { System.debug(a.Id); }
      }
    }`);
    expect(r.ok).toBe(true);
  });
});

describe('comment-first trigger (P13 fix — kind from extension)', () => {
  it('a trigger opening with a comment parses when kind is passed explicitly', async () => {
    const { extractApexAstEdges } = await import('../src/apex-ast-edges.js');
    const src = `/* generated by dlrs — do not edit */
trigger AccountT on Account (before insert) {
  for (Account a : Trigger.new) { a.Description = 'tagged'; }
}`;
    const sniffed = extractApexAstEdges(src, 'AccountT', {});
    expect(sniffed.parseError).toBeDefined(); // the old failure mode
    const explicit = extractApexAstEdges(src, 'AccountT', { kind: 'trigger' });
    expect(explicit.parseError).toBeUndefined();
    expect(explicit.writes).toContain('Account.Description');
  });
});

describe('unresolved dot-chain roots never emit localvar-shaped targets (P14-PHANTOM-edges)', () => {
  it('emits NO reads/writes keyed by an undeclared variable name', async () => {
    const { extractApexAstEdges } = await import('../src/apex-ast-edges.js');
    // `mystery` is never declared — the resolver cannot type it, so neither
    // the read (mystery.Name) nor the write (mystery.Status__c = ...) may
    // emit an edge keyed on the raw token. The declared `acc` resolves to
    // Account and emits normally.
    const src = [
      'public class PhantomGuard {',
      '  public void run(Account acc) {',
      '    String s = mystery.Name;',
      '    mystery.Status__c = s;',
      '    acc.Industry = s;',
      '  }',
      '}',
    ].join('\n');
    const out = extractApexAstEdges(src, 'PhantomGuard', {});
    const all = [...out.reads, ...out.writes];
    expect(all.some((k) => k.startsWith('mystery.'))).toBe(false);
    expect(out.writes).toContain('Account.Industry');
  });
});

describe('innerTypes surface (P14-USAGE-scanner-fp-downgrade)', () => {
  it('returns the inner class names so the import dedupe can drop typed-receiver scanner FPs', async () => {
    const { extractApexAstEdges } = await import('../src/apex-ast-edges.js');
    const src = [
      'public class Outer {',
      '  public class ReportWrapper { public Id id; }',
      '  public class Row { public String name; }',
      '  public void run() {}',
      '}',
    ].join('\n');
    const out = extractApexAstEdges(src, 'Outer', {});
    expect(out.innerTypes).toEqual(['ReportWrapper', 'Row']);
  });
});

/**
 * CR-06 (H5/H5b) — SOQL scope-aware attribution. The buggy `soqlFrom` picked
 * the textually-first FROM (a child-relationship name) as the primary object
 * and swept every FieldName under it, minting phantom parsed-confidence edges
 * (Contacts.Email, mis-keyed semi-join fields) that beat the correct regex
 * edges in dedup. Each field must attribute to its NEAREST query scope's FROM
 * object; child-subquery and TYPEOF fields drop honestly.
 */
describe('SOQL subquery scope attribution (CR-06 / H5)', () => {
  let extract: typeof import('../src/apex-ast-edges.js').extractApexAstEdges;
  beforeAll(async () => {
    ({ extractApexAstEdges: extract } = await import('../src/apex-ast-edges.js'));
  });

  /** Wrap an inline `[SELECT ...]` query as an Apex method body. */
  const inline = (soql: string): readonly string[] =>
    extract(`public class Q { public void run() { List<SObject> r = ${soql}; } }`, 'Q', {})
      .reads;
  /** Wrap the same query as a constant-string `Database.query('...')` literal. */
  const dbquery = (innerSoql: string): readonly string[] =>
    extract(
      `public class Q { public void run() { List<SObject> r = Database.query('${innerSoql}'); } }`,
      'Q',
      {},
    ).reads;

  it('child subquery: fields stay on the PARENT, child relationship is dropped (no phantom)', () => {
    const reads = inline('[SELECT Id, Name, (SELECT Email, Name FROM Contacts) FROM Account]');
    expect(reads).toContain('Account.Id');
    expect(reads).toContain('Account.Name');
    // child fields + relationship name are unresolvable → must NOT be emitted
    expect(reads.some((k) => k.startsWith('Contacts.'))).toBe(false);
    expect(reads).not.toContain('Account.Email');
    expect(reads).not.toContain('Account.Contact');
    // the relationship token never appears as a field segment anywhere
    expect(reads.some((k) => k.includes('Contacts'))).toBe(false);
  });

  it('multiple child subqueries: only the parent fields survive (no second-relationship leak)', () => {
    const reads = inline(
      '[SELECT Id, (SELECT Email FROM Contacts), (SELECT Subject FROM Cases) FROM Account]',
    );
    expect(reads).toEqual(['Account.Id']);
    expect(reads.some((k) => k.includes('Contacts') || k.includes('Cases'))).toBe(false);
    expect(reads).not.toContain('Account.Subject');
    expect(reads).not.toContain('Account.Email');
  });

  it('semi-join: inner fields attribute to the inner FROM object, not the outer', () => {
    const reads = inline(
      '[SELECT Id, Name FROM Account WHERE Id IN (SELECT AccountId FROM Contact WHERE Email != null)]',
    );
    expect(reads).toContain('Account.Id');
    expect(reads).toContain('Account.Name');
    expect(reads).toContain('Contact.AccountId');
    expect(reads).toContain('Contact.Email'); // inner WHERE field keyed to Contact
    // no cross-scope bleed, no FROM-identifier leak
    expect(reads).not.toContain('Account.AccountId');
    expect(reads).not.toContain('Account.Email');
    expect(reads).not.toContain('Account.Contact');
  });

  it('regression: a simple WHERE keeps its fields on the primary object', () => {
    const reads = inline('[SELECT Id FROM Account WHERE Industry = null]');
    expect([...reads].sort()).toEqual(['Account.Id', 'Account.Industry']);
  });

  it('regression: relationship-prefixed outer fields stay verbatim (cross-object traversal)', () => {
    const reads = inline('[SELECT Id, Account.Name FROM Contact]');
    expect(reads).toContain('Contact.Id');
    expect(reads).toContain('Contact.Account.Name');
    expect(reads.some((k) => k.startsWith('Account.'))).toBe(false);
  });

  it('doubly-nested semi-joins partition into three scopes with no bleed', () => {
    const reads = inline(
      '[SELECT Id FROM Account WHERE Id IN (SELECT AccountId FROM Contact WHERE Id IN (SELECT ContactId FROM Case))]',
    );
    expect([...reads].sort()).toEqual([
      'Account.Id',
      'Case.ContactId',
      'Contact.AccountId',
      'Contact.Id',
    ]);
  });

  it('polymorphic TYPEOF: drops the whole clause (WHEN type names + THEN/ELSE fields are phantoms)', () => {
    const reads = inline(
      '[SELECT TYPEOF What WHEN Account THEN Phone WHEN Opportunity THEN Amount ELSE Name END FROM Event]',
    );
    // WHEN tokens are sObject TYPE names, not fields; THEN/ELSE targets are
    // unresolvable to the polymorphic target sObject → emit nothing.
    expect(reads).toEqual([]);
    expect(reads).not.toContain('Event.Account');
    expect(reads).not.toContain('Event.Opportunity');
    expect(reads).not.toContain('Event.Phone');
  });

  it('combined child-subquery + semi-join (MergeCases-shaped): only resolvable scopes survive', () => {
    const reads = inline(
      '[SELECT Id, (SELECT Subject FROM Cases) FROM Contact WHERE Id IN (SELECT ContactId FROM Case)]',
    );
    expect([...reads].sort()).toEqual(['Case.ContactId', 'Contact.Id']);
    expect(reads.some((k) => k.includes('Cases'))).toBe(false);
    expect(reads).not.toContain('Contact.Subject');
  });

  it('child subquery whose relationship coincidentally matches an sObject name is still dropped by structure', () => {
    const reads = inline('[SELECT Id, (SELECT LastName FROM Contact) FROM Account]');
    expect(reads).toEqual(['Account.Id']);
    expect(reads).not.toContain('Contact.LastName');
  });

  it('aggregate function args + GROUP BY fields stay on the primary object', () => {
    const reads = inline('[SELECT COUNT(Id) cnt, Name FROM Account GROUP BY Name]');
    expect(reads).toContain('Account.Id');
    expect(reads).toContain('Account.Name');
  });

  it('a child subquery nested inside a semi-join SELECT is dropped by its NEAREST clause, not the outer WHERE', () => {
    // The inner `(SELECT LastName FROM Notes)` lives in the semi-join's SELECT
    // list; classification must stop at the parent SubQuery boundary so the
    // outer WHERE does not falsely make it a semi-join (which would mint a
    // phantom Notes.LastName).
    const reads = inline(
      '[SELECT Id FROM Account WHERE Id IN (SELECT ContactId, (SELECT LastName FROM Notes) FROM Contact)]',
    );
    expect([...reads].sort()).toEqual(['Account.Id', 'Contact.ContactId']);
    expect(reads.some((k) => k.includes('Notes'))).toBe(false);
  });

  it('Database.query constant-string path is fixed by the same scope-aware logic', () => {
    const childReads = dbquery('SELECT Id, Name, (SELECT Email FROM Contacts) FROM Account');
    expect(childReads).toContain('Account.Id');
    expect(childReads).toContain('Account.Name');
    expect(childReads.some((k) => k.includes('Contacts'))).toBe(false);

    const semiReads = dbquery(
      'SELECT Id, Name FROM Account WHERE Id IN (SELECT AccountId FROM Contact)',
    );
    expect(semiReads).toContain('Account.Id');
    expect(semiReads).toContain('Contact.AccountId');
    expect(semiReads).not.toContain('Account.AccountId');
    expect(semiReads).not.toContain('Account.Contact');
  });
});

/**
 * CR-CAP-06 — callSites: the enclosing CALLER method NAME per cross-class /
 * self call-site. ADDITIVE field (callSites?), AST-path only. Attribution is
 * by the call-site's nearest enclosing MethodDeclaration; a call with NO
 * enclosing method (field/static initializer) maps to '' and is dropped
 * downstream. Original case is preserved (display names).
 */
describe('callSites enclosing-method attribution (CR-CAP-06)', () => {
  let extract: typeof import('../src/apex-ast-edges.js').extractApexAstEdges;
  beforeAll(async () => {
    ({ extractApexAstEdges: extract } = await import('../src/apex-ast-edges.js'));
  });
  const known = new Set(['Callee']);

  it('attributes ONLY the calling method, not the sibling method (two-method discrimination)', () => {
    // Method a() calls Callee.foo(); method b() does NOT call Callee at all.
    // Class-level granularity cannot distinguish; callSites proves it can.
    const src = [
      'public class Caller {',
      '  void a() { Callee.foo(); }',
      '  void b() { Integer x = 1; }',
      '}',
    ].join('\n');
    const out = extract(src, 'Caller', { knownClasses: known });
    const sites = out.callSites ?? [];
    expect(sites).toContainEqual({ callee: 'Callee.foo', callerMethod: 'a' });
    // NOTHING attributed to b — b makes no call.
    expect(sites.some((s) => s.callerMethod === 'b')).toBe(false);
  });

  it('partitions per target method: a()->foo, b()->bar are NOT cross-attributed', () => {
    // The phantom-attribution guard: a() calls foo, b() calls bar. The
    // callSites must keep the (callee, callerMethod) pairing so a downstream
    // consumer never claims b() calls foo.
    const src = [
      'public class Caller {',
      '  void a() { Callee.foo(); }',
      '  void b() { Callee.bar(); }',
      '}',
    ].join('\n');
    const out = extract(src, 'Caller', { knownClasses: known });
    const sites = out.callSites ?? [];
    expect(sites).toContainEqual({ callee: 'Callee.foo', callerMethod: 'a' });
    expect(sites).toContainEqual({ callee: 'Callee.bar', callerMethod: 'b' });
    // a never calls bar; b never calls foo.
    expect(sites.some((s) => s.callee === 'Callee.foo' && s.callerMethod === 'b')).toBe(false);
    expect(sites.some((s) => s.callee === 'Callee.bar' && s.callerMethod === 'a')).toBe(false);
  });

  it('preserves ORIGINAL case in the caller method name (display, not the lowercased seed)', () => {
    const src = [
      'public class Caller {',
      '  void processOpp() { Callee.foo(); }',
      '}',
    ].join('\n');
    const out = extract(src, 'Caller', { knownClasses: known });
    expect(out.callSites ?? []).toContainEqual({
      callee: 'Callee.foo',
      callerMethod: 'processOpp',
    });
  });

  it('a call with NO enclosing method (static initializer) yields callerMethod ""', () => {
    // The static-init call site has no MethodDeclaration ancestor → '' (dropped
    // downstream → absent attribution, never a blank name).
    const src = [
      'public class Caller {',
      '  static { Callee.init(); }',
      '}',
    ].join('\n');
    const out = extract(src, 'Caller', { knownClasses: known });
    const sites = out.callSites ?? [];
    const init = sites.find((s) => s.callee === 'Callee.init');
    expect(init).toBeDefined();
    expect(init?.callerMethod).toBe('');
  });

  it('self-call (bare own-method) carries its enclosing caller method', () => {
    const src = [
      'public class Caller {',
      '  void a() { helper(); }',
      '  void helper() {}',
      '}',
    ].join('\n');
    const out = extract(src, 'Caller', { knownClasses: known });
    expect(out.callSites ?? []).toContainEqual({
      callee: 'Caller.helper',
      callerMethod: 'a',
    });
  });
});

/**
 * CTO #7 / S-6 — cheap AST precision: method-scoped symbol table + own-method
 * return-type propagation. The old file-global `varTypes` map let the last
 * `rec` declaration win class-wide, minting wrong parsed-confidence field
 * edges; call-chained field access (`getAccount().Name`) emitted nothing.
 * AST ≠ compiler: cross-class return types stay unresolved.
 */
describe('method-scoped symbols + own-method return types (CTO #7)', () => {
  let extract: typeof import('../src/apex-ast-edges.js').extractApexAstEdges;
  beforeAll(async () => {
    ({ extractApexAstEdges: extract } = await import('../src/apex-ast-edges.js'));
  });

  it('cross-method variable-name collision: each method keeps its own type', () => {
    // Pre-fix: last FormalParameter `Contact rec` won file-wide, so a()'s
    // rec.Name became Contact.Name (wrong parsed edge).
    const src = [
      'public class Collision {',
      '  void a(Account rec) { String x = rec.Name; }',
      '  void b(Contact rec) { String y = rec.Email; rec.Phone = \'1\'; }',
      '}',
    ].join('\n');
    const out = extract(src, 'Collision', {});
    expect(out.reads).toContain('Account.Name');
    expect(out.reads).toContain('Contact.Email');
    expect(out.writes).toContain('Contact.Phone');
    expect(out.reads).not.toContain('Contact.Name');
    expect(out.reads).not.toContain('Account.Email');
    expect(out.writes).not.toContain('Account.Phone');
  });

  it('method params shadow class fields; sibling methods still see the field', () => {
    const src = [
      'public class Shadow {',
      '  Contact rec;',
      '  void a(Account rec) { String x = rec.Name; }',
      '  void b() { String y = rec.Email; }',
      '}',
    ].join('\n');
    const out = extract(src, 'Shadow', {});
    expect(out.reads).toContain('Account.Name');
    expect(out.reads).toContain('Contact.Email');
    expect(out.reads).not.toContain('Account.Email');
    expect(out.reads).not.toContain('Contact.Name');
  });

  it('own-method return type propagates through bare / this / same-class chains', () => {
    const src = [
      'public class Ret {',
      '  Account getAccount() { return null; }',
      '  void use() {',
      '    String n = getAccount().Name;',
      '    String m = this.getAccount().Industry;',
      '    Ret svc = this;',
      '    String p = svc.getAccount().Type;',
      '  }',
      '}',
    ].join('\n');
    const out = extract(src, 'Ret', {});
    expect(out.reads).toContain('Account.Name');
    expect(out.reads).toContain('Account.Industry');
    expect(out.reads).toContain('Account.Type');
    expect(out.calls).toContain('Ret.getAccount');
    expect(out.callSites ?? []).toContainEqual({
      callee: 'Ret.getAccount',
      callerMethod: 'use',
    });
  });

  it('own-method return type on assignment LHS yields a write', () => {
    const src = [
      'public class Ret {',
      '  Account getAccount() { return null; }',
      '  void use() { getAccount().Description = \'x\'; }',
      '}',
    ].join('\n');
    const out = extract(src, 'Ret', {});
    expect(out.writes).toContain('Account.Description');
    expect(out.calls).toContain('Ret.getAccount');
  });

  it('honesty: cross-class return types do NOT invent field edges', () => {
    // OtherSvc.getAccount() is a call we can see (known class), but we have
    // no return-type table for OtherSvc — must not mint Account.* reads.
    const src = [
      'public class Ret {',
      '  void use(OtherSvc svc) {',
      '    String n = svc.getAccount().Name;',
      '  }',
      '}',
    ].join('\n');
    const out = extract(src, 'Ret', { knownClasses: new Set(['OtherSvc']) });
    expect(out.calls).toContain('OtherSvc.getAccount');
    expect(out.reads.some((r) => r.endsWith('.Name'))).toBe(false);
    expect(out.reads.some((r) => r.startsWith('Account.'))).toBe(false);
  });

  it('this.field.sObjectField peels own instance fields; super.method records extends target', () => {
    const src = [
      'public class Child extends Parent {',
      '  Account mine;',
      '  void use() {',
      '    String a = this.mine.Name;',
      '    super.helper();',
      '  }',
      '}',
    ].join('\n');
    const out = extract(src, 'Child', { knownClasses: new Set(['Parent']) });
    expect(out.reads).toContain('Account.Name');
    expect(out.calls).toContain('Parent.helper');
  });
});
