#!/usr/bin/env node
/* ============================================================================
 * recalibrate.mjs  —  the single source of truth for every COMPUTED number on
 * the sf-intelligence website (Astro edition).
 *
 *   $ node recalibrate.mjs                 # product = parent repo
 *   $ SFI_PRODUCT_DIR=/path node recalibrate.mjs
 *
 * DATA-ONLY. Unlike the pre-Astro version, this NO LONGER templates tools.html
 * or regex-rewrites inline numbers into hand-written pages. It emits data files
 * that Astro consumes at build time (Zod-validated → a shape mismatch is a
 * build error, not a silent regex no-op):
 *   1. src/data/site-data.json  — the calibrated numeric snapshot.
 *   2. src/data/tools.json      — the tool registry, grouped by the product's
 *                                 own capability categories, with whole-sentence
 *                                 summaries plus core / readOnly flags and the
 *                                 default `core` roster (tool-profile.ts).
 *   3. src/data/lastmod.json    — each page's last content change, from git.
 *   4. public/.well-known/mcp/server.json — mirror of packages/cli/server.json.
 *
 * llms.txt, llms-full.txt and /tools.json are NOT written here any more: they
 * are generated by `npm run build` (integrations/geo.mjs, src/pages/tools.json.ts)
 * from the built page list and these data files, so a new page can never be
 * missing from them. The OG card is rendered by scripts/render-og.mjs.
 *
 * Requires the product repo present as the parent (or SFI_PRODUCT_DIR), built
 * (`pnpm -r build` so packages/mcp/dist exists). Node 20+. It must run somewhere
 * with the private product repo — NOT in Cloudflare's build (which only sees the
 * public site subfolder). Run it before every deploy that changes product numbers.
 * ========================================================================== */
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";

const SITE = path.dirname(fileURLToPath(import.meta.url));
function findProduct() {
  if (process.env.SFI_PRODUCT_DIR) return path.resolve(process.env.SFI_PRODUCT_DIR);
  for (const c of [path.resolve(SITE, ".."), path.resolve(SITE, "../sf-intelligence")]) {
    if (fs.existsSync(path.join(c, "packages/mcp"))) return c;
  }
  return path.resolve(SITE, "..");
}
const PRODUCT = findProduct();
const VERSION = JSON.parse(
  fs.readFileSync(path.join(PRODUCT, "packages/cli/package.json"), "utf8"),
).version;

const log = (...a) => console.log(...a);
const warn = (...a) => console.warn("  ⚠ ", ...a);
const die = (m) => { console.error("\n✗ " + m + "\n"); process.exit(1); };
const fmt = (n) => Number(n).toLocaleString("en-US");

/* ---- editorial constants (config, not computed from source) ------------- */
const GATES = [
  "Type-check", "Lint", "Unit tests", "Integration + golden tests",
  "End-to-end smoke", "Natural-language regression", "Analytical correctness eval",
  "Scale benchmarks", "SAST", "Release guard", "Org-data leak scan",
];
const SCALE_BUDGETS = {
  graphImport: "10,000 nodes in under 90 seconds",
  fullRefresh: "1,000 object + field files in under 10 minutes",
  resolve: "p95 under 2 seconds on the CI vault",
};
const PKG_DESC = {
  mcp: (s) => `The ${s.toolCount} read-only tools + router + grounding layer`,
  extractors: () => "Metadata parsing for every Salesforce component type",
  graph: () => "The DuckDB dependency-graph engine",
  cli: () => "The sfi command-line tool",
  patterns: () => "Heuristic recognizers (PII, naming, code quality)",
  parsers: () => "Formula / SOQL / source tokenizers",
  renderers: () => "Markdown vault rendering",
  vault: () => "Vault layout, manifest, freshness",
  "tooling-api": () => "Optional Tooling-API enrichment",
};

/* =========================================================================
 * 1. COMPUTE — the math, straight from product source
 * ======================================================================= */
if (!fs.existsSync(PRODUCT)) die(`Product repo not found at ${PRODUCT}. Set SFI_PRODUCT_DIR.`);
const distIndex = path.join(PRODUCT, "packages/mcp/dist/src/tools/index.js");
if (!fs.existsSync(distIndex)) die(`Built tool registry missing: ${distIndex}\n  Build the product first:  (cd "${PRODUCT}" && pnpm -r build)`);
const { V01_TOOLS } = await import(pathToFileURL(distIndex).href);
if (!Array.isArray(V01_TOOLS)) die("V01_TOOLS not found in the built registry.");
// The default `core` roster (what an MCP host sees in tools/list out of the
// box). Read from the BUILT tool-profile module (exported as a Set), the same
// route as V01_TOOLS, so the site never hand-maintains a copy of the list.
const profileJs = path.join(PRODUCT, "packages/mcp/dist/src/tools/tool-profile.js");
if (!fs.existsSync(profileJs)) die(`Built tool profile missing: ${profileJs}`);
const { CORE_PROFILE_TOOLS: CORE_PROFILE_SET } = await import(pathToFileURL(profileJs).href);
if (!CORE_PROFILE_SET || typeof CORE_PROFILE_SET[Symbol.iterator] !== "function") die("CORE_PROFILE_TOOLS not found in the built tool profile.");
const CORE_PROFILE_TOOLS = [...CORE_PROFILE_SET];
// The rendered tool catalog lists only the ADVERTISED tools: hidden back-compat
// aliases never occupy a tools/list schema slot, so they are not shown as separate
// cards (matches packages/mcp/src/tools/index.ts advertisedTools logic).
const tools = V01_TOOLS.filter((t) => !t.hidden).map((t) => ({
  name: t.name,
  description: String(t.description || "").replace(/\s+/g, " ").trim(),
  // MCP protocol annotation the server advertises for this tool; every tool in
  // the roster is readOnlyHint: true today, but the flag is read, not assumed.
  readOnly: t.annotations?.readOnlyHint === true,
  livePlane: t.livePlane ?? "never",
}));
// The HEADLINE count is the full REGISTERED surface (V01_TOOLS.length), matching
// scripts/product-surface.mjs and the scripts/verify-doc-sync.mjs gate
// (site-data.toolCount === V01_TOOLS.length). The hidden aliases are registered and
// callable — they fold into their canonical tool — so they count toward the
// registered total even though they are not rendered as separate cards.
const advertisedCount = tools.length;
const toolCount = V01_TOOLS.length;
log(`• tools registered (V01_TOOLS): ${toolCount}  (advertised ${advertisedCount})`);

// Concept Model size. Read from the BUILT generated model, the same authoritative
// route used for V01_TOOLS above — not counted out of the curator YAML, so the
// number the site prints is always the one the shipped engine actually loads.
// These figures appear in prose on several pages and in llms.txt; before this was
// computed they drifted (llms.txt carried 142/193 and a stale 94/143 six lines
// apart), which is a citation bug on the one file published for machine citation.
let conceptCount = null;
let conceptRuleCount = null;
try {
  const distModel = path.join(PRODUCT, "packages/mcp/dist/src/knowledge/generated/concept-model.js");
  const { CONCEPTS, CONCEPT_RULES } = await import(pathToFileURL(distModel).href);
  conceptCount = Object.keys(CONCEPTS).length;
  conceptRuleCount = CONCEPT_RULES.length;
  log(`• concept model:                ${conceptCount} concepts / ${conceptRuleCount} rules`);
} catch (e) {
  warn("built concept-model not found; concept/rule counts left untouched.", e.message);
}

let surface = {};
try {
  surface = JSON.parse(execSync("node scripts/product-surface.mjs", { cwd: PRODUCT, encoding: "utf8" }));
  log(`• component types:              ${surface.componentTypeCount}`);
  log(`• edge types:                   ${surface.edgeTypeCount}`);
  log(`• skills:                       ${surface.skillCount}`);
  log(`• agents:                       ${surface.agentCount ?? 0}`);
  log(`• slash commands:               ${surface.slashCommandCount}`);
  if (surface.toolCount && surface.toolCount !== toolCount)
    warn(`product-surface toolCount (${surface.toolCount}) != V01_TOOLS length (${toolCount}); trusting V01_TOOLS.`);
  // Prefer ProductManifest concept counts when present (same registries as
  // eval/product-manifest.json) so site-data cannot disagree with the SSOT.
  if (surface.conceptCount != null) conceptCount = surface.conceptCount;
  if (surface.conceptRuleCount != null) conceptRuleCount = surface.conceptRuleCount;
} catch (e) {
  warn("product-surface.mjs failed; skill/command/type counts will be left untouched.", e.message);
}

function walkTests(dir, acc = []) {
  let entries; try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return acc; }
  for (const e of entries) {
    if (e.name === "node_modules" || e.name === "dist") continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walkTests(p, acc);
    else if (e.name.endsWith(".test.ts")) acc.push(p);
  }
  return acc;
}
const countCases = (file) => (fs.readFileSync(file, "utf8").match(/^[ \t]*(it|test)\(/gm) || []).length;
const pkgRoot = path.join(PRODUCT, "packages");
const packages = [];
for (const name of fs.readdirSync(pkgRoot).sort()) {
  const dir = path.join(pkgRoot, name);
  if (!fs.statSync(dir).isDirectory()) continue;
  const files = walkTests(dir);
  if (!files.length) continue;
  const cases = files.reduce((a, f) => a + countCases(f), 0);
  packages.push({ name, files: files.length, cases });
}
packages.sort((a, b) => b.cases - a.cases);
const totalCases = packages.reduce((a, p) => a + p.cases, 0);
const totalFiles = packages.reduce((a, p) => a + p.files, 0);
const packageCount = packages.length;
log(`• unit test cases:              ~${fmt(totalCases)} across ${totalFiles} files in ${packageCount} packages`);

let integrationSuiteCount = 0;
try {
  integrationSuiteCount = fs.readdirSync(path.join(PRODUCT, "tests/integration")).filter((f) => f.endsWith(".test.ts")).length;
} catch { warn("tests/integration not found; integration count left as-is."); }
log(`• integration suites:           ${integrationSuiteCount}`);

const approxTests = Math.floor(totalCases / 100) * 100;

const stats = {
  generatedAt: new Date().toISOString(),
  version: VERSION,
  toolCount,
  // Size of the default `core` profile: the tools advertised and directly
  // invokable out of the box (the rest run through sfi.run_analysis).
  coreToolCount: CORE_PROFILE_TOOLS.length,
  // Tools listed in the catalog: registered minus hidden back-compat aliases.
  listedToolCount: advertisedCount,
  skillCount: surface.skillCount ?? null,
  agentCount: surface.agentCount ?? null,
  commandCount: surface.slashCommandCount ?? null,
  componentTypeCount: surface.componentTypeCount ?? null,
  edgeTypeCount: surface.edgeTypeCount ?? null,
  conceptCount,
  conceptRuleCount,
  tests: { packages, totalCases, totalFiles, packageCount, approx: approxTests },
  integrationSuiteCount,
  gates: GATES, gateCount: GATES.length,
  scaleBudgets: SCALE_BUDGETS,
  packageDescriptions: packages.map((p) => ({
    name: p.name,
    files: p.files,
    cases: p.cases,
    description: (PKG_DESC[p.name] || (() => `${p.name} package tests`))({ toolCount }),
  })),
};

/* =========================================================================
 * 2. snapshot + diff
 * ======================================================================= */
const dataDir = path.join(SITE, "src/data");
fs.mkdirSync(dataDir, { recursive: true });
const dataPath = path.join(dataDir, "site-data.json");
let prev = null;
try { prev = JSON.parse(fs.readFileSync(dataPath, "utf8")); } catch {}
fs.writeFileSync(dataPath, JSON.stringify(stats, null, 2) + "\n");

/* =========================================================================
 * 3. tools.json — grouped registry for the /tools page, /tools.json and the
 *    llms-full.txt catalog (both generated at build from this file).
 * ======================================================================= */
const normalizeSeoText = (s) => s.replace(/[–—]/g, "-").replace(/…/g, "...");

/**
 * A tool's catalog summary: whole sentences only.
 *
 * The previous one-liner cut at the first ". " and then hard-sliced at 165
 * characters, so 111 of 226 entries in llms-full.txt (the file published for
 * verbatim machine citation) ended mid-word with "...". Now: split on real
 * sentence ends (not after e.g. / i.e. / vs. / etc. / a dotted API name), keep
 * up to two sentences inside ~300 characters, and when the FIRST sentence alone
 * is longer than that, drop its parenthetical asides and then end it at its last
 * top-level clause boundary (" — ", "; ", ": ", ", ") instead of mid-word.
 */
const SUMMARY_MAX = 300;
const ABBREV = /(?:\be\.g|\bi\.e|\bvs|\betc|\bcf|\bapprox|\bincl|\bNo)\.$/i;
function splitSentences(text) {
  const out = [];
  let start = 0;
  let depth = 0; // ( [ depth — never end a sentence inside an aside
  let tick = false; // inside `code`
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (c === "`") tick = !tick;
    if (tick) continue;
    if (c === "(" || c === "[") depth++;
    else if ((c === ")" || c === "]") && depth > 0) depth--;
    if (depth > 0 || !/[.!?]/.test(c)) continue;
    const next = text[i + 1];
    if (next !== undefined && next !== " ") continue; // "sfi.resolve", "0.4.0"
    const head = text.slice(start, i + 1);
    if (ABBREV.test(head)) continue;
    const after = text.slice(i + 1).trimStart();
    if (after && !/^[A-Z`"'(\[*_]/.test(after)) continue; // "... etc. and more"
    out.push(head.trim());
    start = i + 1;
  }
  const rest = text.slice(start).trim();
  if (rest) out.push(rest);
  return out;
}
/** Remove balanced (...) asides that sit outside backticks. */
function dropParentheticals(s) {
  let out = "";
  let depth = 0;
  let tick = false;
  for (const c of s) {
    if (c === "`" && depth === 0) tick = !tick;
    if (!tick && c === "(") { depth++; continue; }
    if (!tick && c === ")" && depth > 0) { depth--; continue; }
    if (depth === 0) out += c;
  }
  // A paired " — … — " is an aside too: "X, Y — detail about Y — and Z".
  // Replaced by a comma: in a list the dash pair stands where a comma would.
  out = out.replace(/ — [^—]+? — /g, ", ");
  return out.replace(/\s+([,.;:])/g, "$1").replace(/,(\s*,)+/g, ",").replace(/\s{2,}/g, " ").trim();
}
/** Cut at the last top-level clause boundary at or before `max`. */
function clauseCut(s, max) {
  let tick = false;
  let depth = 0;
  let best = { strong: -1, comma: -1 };
  for (let i = 0; i < Math.min(s.length, max); i++) {
    const c = s[i];
    if (c === "`") tick = !tick;
    if (tick) continue;
    if (c === "(" || c === "[") depth++;
    else if ((c === ")" || c === "]") && depth > 0) depth--;
    if (depth > 0) continue;
    if (s.startsWith(" — ", i) || s.startsWith(" - ", i) || s.startsWith("; ", i) || s.startsWith(": ", i)) best.strong = i;
    else if (s.startsWith(", ", i)) best.comma = i;
  }
  const at = best.strong > 60 ? best.strong : best.comma > 60 ? best.comma : -1;
  if (at === -1) return null;
  return s.slice(0, at).replace(/[,;:\s—-]+$/, "") + ".";
}
const summaryStats = { whole: 0, trimmedAsides: 0, clause: 0, wordCut: 0 };
function summarize(description) {
  const sentences = splitSentences(description);
  let first = sentences[0] ?? description;
  if (!/[.!?]$/.test(first)) first += ".";
  if (first.length <= SUMMARY_MAX) {
    let s = first;
    const second = sentences[1];
    if (second && (s + " " + second).length <= SUMMARY_MAX && !/^(Args|Example|Returns? shape|Input)\b/i.test(second)) s += " " + second;
    summaryStats.whole++;
    return normalizeSeoText(s);
  }
  const lean = dropParentheticals(first);
  if (lean.length <= SUMMARY_MAX) { summaryStats.trimmedAsides++; return normalizeSeoText(lean); }
  const cut = clauseCut(lean, SUMMARY_MAX);
  if (cut) { summaryStats.clause++; return normalizeSeoText(cut); }
  summaryStats.wordCut++;
  return normalizeSeoText(lean.slice(0, SUMMARY_MAX).replace(/\s+\S*$/, "") + "...");
}

const bare = (n) => n.replace(/^sfi\./, "");

/*
 * GROUPS — derived from the product's own taxonomy first.
 *
 * Primary source: the curated capability map the server itself publishes
 * (`CATEGORIES` in packages/mcp/src/tools/capabilities.ts, the same map
 * `sfi.capabilities` returns). A tool listed in a category goes there.
 *
 * That map names REPRESENTATIVE tools only (about half the roster), so the
 * remainder is placed by name rules below, written as a deny-list over the
 * product category ids — never a hand-kept allow-list of every tool, which is
 * how 51 tools (review_change, object_360 among them) ended up under "Other".
 * "Other" is capped: more than OTHER_MAX tools there fails recalibration, so a
 * new tool family has to be placed deliberately.
 */
const OTHER_MAX = 5;
let CATEGORIES = [];
try {
  ({ CATEGORIES } = await import(pathToFileURL(path.join(PRODUCT, "packages/mcp/dist/src/tools/capabilities.js")).href));
} catch (e) {
  die(`Could not load the product capability map (packages/mcp/dist/src/tools/capabilities.js): ${e.message}`);
}
const SITE_ONLY_GROUPS = {
  orientation: "Getting oriented",
  industries: "Industries: OmniStudio & CPQ",
  "cross-org": "Cross-org & fleet",
  other: "Other",
};
const GROUP_ORDER = ["orientation", ...CATEGORIES.map((c) => c.id), "industries", "cross-org", "other"];
const groupLabel = (id) => SITE_ONLY_GROUPS[id] ?? CATEGORIES.find((c) => c.id === id)?.title ?? id;
const productCategoryOf = new Map();
for (const c of CATEGORIES) for (const t of c.tools) if (!productCategoryOf.has(t)) productCategoryOf.set(t, c.id);

const NAME_RULES = [
  ["orientation", (n) => ["capabilities", "list_analyses", "describe_analysis", "run_analysis", "route_question", "guidance", "disambiguate_concepts", "org_card"].includes(n)],
  ["industries", (n) => n.startsWith("omni") || n.startsWith("cpq_") || ["integration_procedure_chain", "datatransform_field_map", "decision_table_browse"].includes(n)],
  ["cross-org", (n) => n.startsWith("fleet_") || n.endsWith("_across_vaults") || ["compare_vaults", "promotion_readiness"].includes(n)],
  ["live", (n) => n.startsWith("live_") || n === "blast_radius_live"],
  ["impact", (n) => n.startsWith("what_if_") || ["get_subgraph", "find_dependency_cycles", "value_change_audit", "why_field_changed", "field_change_advisor", "record_delete_impact", "find_formula_references", "find_component_usages", "find_code_usages"].includes(n)],
  ["access", (n) => /permission|permset|profile|access|who_can|sharing|security/.test(n) || ["user_ability", "layout_for_user", "how_to_see", "app_access", "tab_availability", "recordtype_availability", "lightning_pages", "layout_assignments", "persona_unused_grants"].includes(n)],
  ["automation", (n) => n.startsWith("apex_") || n.startsWith("automation_") || n.includes("test") || n.startsWith("find_hardcoded_values") || ["code_quality_audit", "find_clone_patterns", "process_builder_migration_candidates", "async_chain_depth", "scheduled_job_catalog", "action_chain"].includes(n)],
  ["integration", (n) => ["event_subscribers", "installed_package_catalog"].includes(n)],
  ["docs", (n) => n.startsWith("generate_") || ["get_naming_convention_report", "domain_clusters", "field_mapping_between_objects", "export_manifest"].includes(n)],
  ["govern", (n) => n.startsWith("baseline_") || n.startsWith("unused_") || n.endsWith("_annotation") || ["annotations", "retrieve_blindspot_report", "empty_queues_and_groups", "what_changed_since_refresh", "org_history", "component_history", "component_as_of"].includes(n)],
  ["find", (n) => n.startsWith("search_") || n.startsWith("find_") || n === "lookup_record"],
  ["understand", (n) => ["field_provenance", "object_360", "compare_components"].includes(n)],
];
const groupOf = (name) => {
  const fromProduct = productCategoryOf.get(name);
  if (fromProduct) return fromProduct;
  const n = bare(name);
  for (const [id, test] of NAME_RULES) if (test(n)) return id;
  return "other";
};

const core = CORE_PROFILE_TOOLS;
{
  const listed = new Set(tools.map((t) => t.name));
  const unlisted = core.filter((n) => !listed.has(n));
  if (unlisted.length) die(`Core tools missing from the advertised registry: ${unlisted.join(", ")}`);
}
const coreSet = new Set(core);
const buckets = new Map(GROUP_ORDER.map((id) => [id, []]));
for (const t of tools) {
  const id = groupOf(t.name);
  if (!buckets.has(id)) buckets.set(id, []);
  buckets.get(id).push(t);
}
const otherTools = buckets.get("other") ?? [];
if (otherTools.length > OTHER_MAX) {
  die(
    `${otherTools.length} tools fall into "Other" (max ${OTHER_MAX}): ${otherTools.map((t) => t.name).join(", ")}.\n` +
      "  Add them to a product category (packages/mcp/src/tools/capabilities.ts) or a NAME_RULES entry in recalibrate.mjs.",
  );
}
const sections = [...buckets.entries()].filter(([, arr]) => arr.length)
  .map(([id, arr]) => ({
    id,
    label: normalizeSeoText(groupLabel(id)),
    tools: arr.map((t) => ({
      name: t.name,
      description: summarize(t.description),
      core: coreSet.has(t.name),
      readOnly: t.readOnly,
      livePlane: t.livePlane,
    })),
  }));
const listedToolCount = sections.reduce((n, s) => n + s.tools.length, 0);
log(`• tool groups:                  ${sections.map((s) => `${s.id}=${s.tools.length}`).join(" ")}`);
log(`• summaries:                    ${summaryStats.whole} whole sentences, ${summaryStats.trimmedAsides} asides dropped, ${summaryStats.clause} clause-ended, ${summaryStats.wordCut} word-cut`);
fs.writeFileSync(
  path.join(dataDir, "tools.json"),
  JSON.stringify(
    { generatedAt: stats.generatedAt, version: VERSION, toolCount, listedToolCount, coreToolCount: stats.coreToolCount, core, sections },
    null,
    2,
  ) + "\n",
);

/* =========================================================================
 * 4. lastmod.json — each page's last real content change, from git history.
 *
 * Cloudflare Pages builds from a shallow clone, where `git log -- <file>`
 * returns HEAD for every file: every sitemap <lastmod> read the same
 * 2026-10-03T18:48:27Z. So the dates are computed HERE, from the full-history
 * local repo, and committed. The build only reads this file; a page that is not
 * in it gets no <lastmod> at all (omitting beats stamping the deploy date).
 * ======================================================================= */
const PAGES_DIR = path.join(SITE, "src/pages");
const lastmodPath = path.join(dataDir, "lastmod.json");
const gitOut = (args) => execSync(`git ${args}`, { cwd: SITE, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
let shallow = true;
try { shallow = gitOut("rev-parse --is-shallow-repository") !== "false"; } catch { /* no git: treat as shallow */ }
if (shallow) {
  warn("git history is shallow or missing; src/data/lastmod.json left unchanged (never stamp HEAD for every page).");
} else {
  const routes = {};
  const walkPages = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) { walkPages(full); continue; }
      if (!/\.(astro|md|mdx)$/.test(e.name) || e.name.startsWith("_") || e.name.includes("[")) continue;
      const rel = path.relative(PAGES_DIR, full).replace(/\\/g, "/").replace(/\.(astro|md|mdx)$/, "");
      if (rel === "404") continue;
      const route = "/" + rel.replace(/(^|\/)index$/, "");
      const iso = gitOut(`log -1 --format=%cI -- "${full}"`);
      if (iso) routes[route.replace(/\/$/, "") || "/"] = new Date(iso).toISOString();
    }
  };
  walkPages(PAGES_DIR);
  // Markdown guides (src/content/guides/<section>/<name>.md) render at
  // /<section>/<name> through a dynamic [slug] route the walk above skips.
  const GUIDES_DIR = path.join(SITE, "src/content/guides");
  if (fs.existsSync(GUIDES_DIR)) {
    for (const section of fs.readdirSync(GUIDES_DIR, { withFileTypes: true })) {
      if (!section.isDirectory()) continue;
      for (const f of fs.readdirSync(path.join(GUIDES_DIR, section.name))) {
        if (!/\.mdx?$/.test(f)) continue;
        const full = path.join(GUIDES_DIR, section.name, f);
        const iso = gitOut(`log -1 --format=%cI -- "${full}"`);
        if (iso) routes[`/${section.name}/${f.replace(/\.mdx?$/, "")}`] = new Date(iso).toISOString();
      }
    }
  }
  const sorted = Object.fromEntries(Object.entries(routes).sort(([a], [b]) => a.localeCompare(b)));
  fs.writeFileSync(lastmodPath, JSON.stringify(sorted, null, 2) + "\n");
  log(`• lastmod dates:                ${Object.keys(sorted).length} routes from git history`);
}

/* =========================================================================
 * 5. /.well-known/mcp/server.json — byte-for-byte mirror of the registry
 *    manifest. Cloudflare builds only the website/ folder, so the copy is made
 *    here; scripts/verify-doc-sync.mjs fails when the two differ.
 * ======================================================================= */
const serverJsonSrc = path.join(PRODUCT, "packages/cli/server.json");
const serverJsonDst = path.join(SITE, "public/.well-known/mcp/server.json");
if (fs.existsSync(serverJsonSrc)) {
  fs.mkdirSync(path.dirname(serverJsonDst), { recursive: true });
  fs.copyFileSync(serverJsonSrc, serverJsonDst);
  log("• server.json mirrored:         public/.well-known/mcp/server.json");
} else {
  warn("packages/cli/server.json not found; /.well-known/mcp/server.json not refreshed.");
}

/* =========================================================================
 * 6. report
 * ======================================================================= */
const metrics = {
  toolCount, coreToolCount: stats.coreToolCount, listedToolCount, skillCount: stats.skillCount, commandCount: stats.commandCount,
  conceptCount: stats.conceptCount, conceptRuleCount: stats.conceptRuleCount,
  componentTypeCount: stats.componentTypeCount, edgeTypeCount: stats.edgeTypeCount,
  unitTestCases: totalCases, testPackages: packageCount, integrationSuites: integrationSuiteCount, ciGates: stats.gateCount,
};
log("\nMETRIC                 PREVIOUS -> NOW");
for (const [k, v] of Object.entries(metrics)) {
  const old = prev ? (
    k === "unitTestCases" ? prev.tests?.totalCases :
    k === "testPackages" ? prev.tests?.packageCount :
    k === "integrationSuites" ? prev.integrationSuiteCount :
    k === "ciGates" ? prev.gateCount :
    prev[k]
  ) : undefined;
  const moved = prev && old !== v;
  log(`  ${k.padEnd(20)} ${String(old ?? " - ").padStart(8)} -> ${String(v).padStart(6)} ${moved ? "  ← changed" : ""}`);
}
log("\nDATA WRITTEN: src/data/site-data.json, src/data/tools.json, src/data/lastmod.json, public/.well-known/mcp/server.json");
log("llms.txt, llms-full.txt and /tools.json are generated by `npm run build` from these files.");
log("OG image: run `node scripts/render-og.mjs` after a hero copy change.");
log("✓ recalibration complete.\n");
