import { DuckDBInstance } from '@duckdb/node-api';
const db = await DuckDBInstance.create(process.argv[2], {access_mode:'READ_ONLY'});
const c = await db.connect();
const q = async (sql)=>{const r= await c.runAndReadAll(sql); return r.getRowObjectsJS();};
const out = {};
out.condReadsFromAll = await q("SELECT COUNT(*)::INT n FROM edges WHERE edge_type='readsFrom' AND from_id LIKE 'ConditionalContext:%'");
out.condVR = await q("SELECT COUNT(*)::INT n FROM edges WHERE edge_type='readsFrom' AND from_id LIKE 'ConditionalContext:ValidationRule:%'");
out.condByFam = await q(`SELECT split_part(from_id,':',2) fam, COUNT(*)::INT n FROM edges WHERE edge_type='readsFrom' AND from_id LIKE 'ConditionalContext:%' GROUP BY 1 ORDER BY 2 DESC`);
out.sample = await q("SELECT from_id,to_id,edge_type,confidence,source,properties_json FROM edges WHERE edge_type='readsFrom' AND from_id LIKE 'ConditionalContext:ValidationRule:%' LIMIT 3");
console.log(JSON.stringify(out,null,1));
